### ISSUE TITLE
[Bug] - Python - "Unable to reach app. Please try again." with sample 54.teams-task-module

### ISSUE THREAD

**Issue by sagarm09** [microsoft/BotBuilder-Samples#3314] opened 2021-06-10 14:52 UTC
## Sample information
1. Sample type: [https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/python/54.teams-task-module]
2. Sample language: [Python]
3. Sample name: [54.teams-task-module]

## Describe the bug
We tried invoking a task module using bot adaptive and hero cards. For the adaptive card the bot did not receive anything and the task module wasn't invoked. Whereas, for the hero card, a pop up comes up with an error message as shown below.

## To Reproduce
1. Go to 'https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/python/54.teams-task-module'
2. Download above solution and follow the steps from README.md
3. See error - On click of Adaptive card button - "Unable to reach app. Please try again"

## Expected behavior
On click of Hero card/ Adaptive card button task module should open.

## Screenshots
![image](https://user-images.githubusercontent.com/85691087/121545172-e6d22880-ca27-11eb-9644-266beb6126b6.png)
![image](https://user-images.githubusercontent.com/85691087/121545225-f3568100-ca27-11eb-9e95-44ea90ab3cdb.png)
![image](https://user-images.githubusercontent.com/85691087/121545236-f6ea0800-ca27-11eb-9ca0-135570e4f5fb.png)
![image](https://user-images.githubusercontent.com/85691087/121545298-06695100-ca28-11eb-850d-efae1a077380.png)
![image](https://user-images.githubusercontent.com/85691087/121545458-2e58b480-ca28-11eb-9f09-2fb2e25d0b02.png)

**Comment by mrivera-ms** [comment] 2021-06-14 18:21
@dmvtech, are there any updates on this?

**Comment by dmvtech** [comment] 2021-06-14 23:38
@sa9arm Thank you for bringing to our attention. I am able to reproduce. Investigating now and will keep you updated.

**Comment by dmvtech** [comment] 2021-06-15 17:21
Not sure what is going on here, currently having personal issues debugging. Adding @axelsrz for visibility.

**Comment by dubi0us** [comment] 2021-06-21 23:49
I'm having this issue as well.  Is this possible due to using ngrok?

**Comment by dmvtech** [comment] 2021-06-24 23:43
I can still reproduce without ngrok. Still investigating cause.

**Comment by Zerryth** [comment] 2021-06-24 23:59
Can confirm I get the same results as @sagarm09 and the others are getting.

Just to be completely explicit, repro steps:
1. Create Azure Bot resource in Azure portal:
   -  ![image](https://user-images.githubusercontent.com/35248895/123346182-8f928480-d50c-11eb-85d0-afe009036ed2.png)

2. Run ngrok `.\ngrok http 3978 -host-header="localhost:3978"`
3. Copy ngrok forwarding address into Azure Bot > Configuration > Messaging endpoint
   - ![image](https://user-images.githubusercontent.com/35248895/123346318-d6807a00-d50c-11eb-9238-45d7957d8cf0.png)
4. Copy all the appropriate values following sample 54's README inside the bot (like in `config.py`, `manifest.json`)
5. Zipping up contents of `teams_app_manifest` and uploading into Teams
6. Running bot locally with `py app.py` 

Get error clicking on Adaptive Card button in conversation
![image](https://user-images.githubusercontent.com/35248895/123346608-8c4bc880-d50d-11eb-833e-1f79f089fbd0.png)

**Comment by Zerryth** [comment] 2021-06-25 17:17
Few more details:

<details>
   <summary>manifest.json: be sure to edit to include the bot's AppId as well as edit validDomains</summary>

```
  "validDomains": [
    "YourDeployedBotUrl.com",
    "localhost",
    "localhost:3978",
    "179a5db5b606.ngrok.io"
  ]
```

</details> 

<details>
    <summary>Plugging in a local copy of the python SDK into sample 54 does not help, as it doesn't appear that the bot is ever reached at all</summary>

*requirements.txt* - point packages to local copies from cloned SDK
```
msrest
botbuilder-schema>="C:\BF\py\task-mod\botbuilder-python\libraries\botbuilder-schema"
botframework-connector>="C:\BF\py\task-mod\botbuilder-python\libraries\botframework-connector"
botbuilder-integration-aiohttp>="C:\BF\py\task-mod\botbuilder-python\libraries\botbuilder-integration-aiohttp"

```
In terminal, where bot is run, there isn't any logging activity, as it appears the request from clicking on Adaptive Card in Teams never reaches the bot it seems

![image](https://user-images.githubusercontent.com/35248895/123461424-f744e000-d59d-11eb-85be-3c6ba1075a24.png)


</details>

<details>
   <summary>Error in dev console when using web version of Teams</summary>

![image](https://user-images.githubusercontent.com/35248895/123461655-34a96d80-d59e-11eb-81b5-e54eb1889a3e.png)


</details>

____
To state the obvious, it appears that these issues are from Teams not being able to call the bot. I could see if this is ngrok-related by trying to call sample 54.teams-task-module bot that's deployed rather than using ngrok

It's possible that there was a change of behavior in Teams that's breaking--or perhaps there was  change in Teams that requires the bot to be set up differently, but as of now the bot samples have remained the same.

**Comment by tracyboehrer** [comment] 2021-06-29 17:45
I am unable to reproduce this.  There is one step missing in the README.  Updating the "BaseUrl" in config.py, but it doesn't seem to matter for the Apaptive Cards button.

### My steps

1) Created the bot registration
2) Started ngrok (per README)
3) Updated the Azure Bot Messaging Endpoint (via the Azure Portal) to be {ngrok-url}/api/messages
4) Updated config.py
    a) `MicrosoftAppId`
    b) `MicrosoftAppPassword`
    c) `BaseUrl`  (set to the ngrok url)
5) Update `CustomForm.html` with the `MicrosoftAppId`
6) Start the bot locally
7) Update teams_app_manifest/manifest.json
    a) Update `<<YOUR-MICROSOFT-APP-ID>>` in both locations
    b) Update `validDomains` to the ngrok hostname (not the entire URL)
 8) In Teams
    a) Import the `manifest.json`.  You don't actually need to create the zip.  Just navigate to the manifest.json.  Though it won't matter which method you use.
    b) Test & Distribute

**Comment by dubi0us** [comment] 2021-06-30 14:58
> I am unable to reproduce this. 
Are you saying that you got the sample working?

**Comment by tracyboehrer** [comment] 2021-06-30 16:50
> _> I am unable to reproduce this._
> Are you saying that you got the sample working?

Yes.  I was unable to reproduce the described "Unable to reach app" error.  The Adaptive Cards button prompted for text, and sent it back to the bot.  The other options worked as well.

**Comment by dubi0us** [comment] 2021-06-30 20:58
Fantastic, could you please share your configuration files.  Obviously there's some minor miscommunication going on and it'd be very helpful to see the specifics of your implementation in order to fix whatever problem is on my end.

**Comment by dmvtech** [comment] 2021-06-30 22:38
@dubi0us Let me work on getting that for you. Obviously the readme needs to be updated as well.

**Comment by tracyboehrer** [comment] 2021-07-01 14:19
Hold tight.  There is something funny.  Looking into it.

**Comment by dmvtech** [comment] 2021-07-06 22:54
@sagarm09 

This is resolved in R14. If you wish to test from the release candidate, you can update the requirements.txt to use `4.14.0rc3` for the bot packages and then pip install. Otherwise, it should be out sometime soon.

**Comment by sagarm09** [comment] 2021-07-08 13:37
@dmvtech, @tracyboehrer 
 
Thank you for the solution its working now 👍 but I have a query that below library is not used anywhere in the code (botbuilder-integration-aiohttp).

![image](https://user-images.githubusercontent.com/85691087/124929261-fdb36d00-e01d-11eb-83a3-b7a5ca72b614.png)

I can see it used separately in the code could you please help me to understand how/where it referenced in the code as a single library "botbuilder-integration-aiohttp" ?

![image](https://user-images.githubusercontent.com/85691087/124930351-e1fc9680-e01e-11eb-8823-3b61cdcd4a01.png)

**Comment by axelsrz** [comment] 2021-07-13 18:29
Looking into the sample, the library is not used. This means the dependency can be replaced by botbuilder-core.

Will be closing this issue due to original problem being solved.

**Closed by axelsrz** 2021-07-13 18:29 UTC
Labels: Bot Services, bug, customer-replied-to, customer-reported, needs-triage

**Comment by winpisces** [comment] 2024-01-17 19:45
It appears that the issue can be resolved by adjusting the Token Exchange URL. Specifically, you should use the Application ID URL that you obtained in step 1.3 as stated in the [Microsoft Teams Samples Bot Conversation SSO Quickstart Setup Guide](hxxps://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/bot-conversation-sso-quickstart/BotSSOSetup.md). While many samples and documents on the internet suggest leaving this field blank, I found that filling in the Token Exchange URL field effectively resolved the "Unable to reach app. Please try again" error in Python.
