### ISSUE TITLE
QnAMaker link broken

### ISSUE THREAD

**Issue by CathyQian** [Microsoft/BotBuilder-Samples#567] opened 2018-09-27 18:30 UTC
## Sample information
1. Sample type: Samples
2. Sample language: C#
3. Sample name: 11.QnAMaker

## Describe the bug
In the README.MD file, two links, to "here" and "sample.qna" respectively, in the following sentence in the prerequisite section are broken: "Follow instructions here to import the sample.qna to your newly created QnA Maker service.""

The right link to "here" should be: https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/tutorials/migrate-knowledge-base
The right link to "sample.qna" should be: https://github.com/Microsoft/BotBuilder-Samples/blob/v4/samples/csharp_dotnetcore/11.qnamaker/CognitiveModels/sample.qna

**Comment by vishwacsena** [comment] 2018-09-27 21:11
Possible dupe of #562

**Comment by JasonSowers** [comment] 2018-09-27 21:30
addressed in #573

**Closed by JasonSowers** 2018-09-27 21:30 UTC
Labels: approved, bug
