### ISSUE TITLE
Generated form dialog of 'any string' contains unexpected '${property}' in content

### ISSUE THREAD

**Issue by yeze322** [microsoft/BotBuilder-Samples#2956] opened 2020-11-25 01:48 UTC
## Versions
@microsoft/bf-generate-library/4.10.0 win32-x64 node v12.14.1

## Describe the bug
Give a clear and concise description of what the bug is.

In Composer, create a form property typed with "any string", the generated dialog contains unexpected '${property}' in content.

For example
    - In the Trigger name: `age - Add(@${property}Entity)`
    - In the expression value `- ${confirmationText('age', @${property}Entity)}`.

#### Schema:
![image](https://user-images.githubusercontent.com/8528761/100067538-5bb98880-2e71-11eb-8e75-4b71a6698c1e.png)

#### Generated Expression value
![image](https://user-images.githubusercontent.com/8528761/100076198-e30bf980-2e7b-11eb-9336-45220ddcd56c.png)

#### Generated Trigger name:
![image](https://user-images.githubusercontent.com/8528761/100067511-51978a00-2e71-11eb-9f7b-f297c216722a.png)

## To Reproduce
1. Add a form property typed with "any string"
2. Generate the dialog with cli
3. Check the generated dialog content

## Expected behavior
Give a clear and concise description of what you expected to happen.

The "${property}" needs to be resolved as the given property name.

## Additional context

[bug]

**Comment by gandiddi** [comment] 2024-05-23 15:45
Unable to reproduce the issue. It was resolved in the [BotFramework-Composer](https://github.com/microsoft/BotFramework-Composer) repository. Hence, the issue is being closed.
<img width="257" alt="image" src="https://github.com/microsoft/BotBuilder-Samples/assets/164224646/6b57664a-23b6-4cfe-9213-0dcb8c2111b0">

**Closed by gandiddi** 2024-05-23 15:45 UTC
