### ISSUE TITLE
Keynotfound exception for dialogstate or accessors' states

### ISSUE THREAD

**Issue by piplupnoil** [Microsoft/BotBuilder-Samples#1261] opened 2019-02-22 00:18 UTC
Whenever I run any dotnet bot samples that involves bot accessors, I get "Keynotfound" exceptions eg: 
<img width="846" alt="capture" src="https://user-images.githubusercontent.com/37196330/53210801-f9748980-35f3-11e9-9487-2ec3d1517948.PNG">
This was from the multilingual bot. 

Any solutions?

**Comment by jwiley84** [comment] 2019-02-27 17:14
Have you put your translation key into the bot?

**Comment by piplupnoil** [comment] 2019-02-27 17:59
Yes I have put the translation key in the appsettings file.

**Comment by CoHealer** [comment] 2019-03-04 19:14
@tdurnford, can you please assist?

**Comment by tdurnford** [comment] 2019-03-04 23:58
@piplupnoil 

Are you just opening the sample, adding your translation key from your Azure Cognitive Service, building and running the project?

**Comment by piplupnoil** [comment] 2019-03-07 17:59
Yes that is what I'm doing

**Comment by tdurnford** [comment] 2019-03-08 23:37
@piplupnoil 

What version of the SDK are you using, are you trying to run the most up to date samples, and what platform are you running the samples on (Windos, MacOS, or Linux)? Also, could you provide a stack trace for your issue?

Thanks

**Comment by tdurnford** [comment] 2019-03-11 18:09
@piplupnoil 

After looking into the source code, it looks like the error you are seeing is a designed exception. If the key is not present in the dictionary, it will raise the error, and when it is caught, it signals IPropertyAccesor that a default value should be computed. You can take a look at the code [here](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder/BotState.cs#L176) for more details.

Thank you @EricDahlvang for your direction.

**Comment by CoHealer** [comment] 2019-03-11 18:24
Closing as by design, thanks @tdurnford. @piplupnoil, if this does not address your question please let us know.

**Closed by CoHealer** 2019-03-11 18:24 UTC
Labels: Support
