### ISSUE TITLE
Attachment.name has prefix fromClient:: when coming from WebChat

### ISSUE THREAD

**Issue by HesselWellema** [microsoft/BotBuilder-Samples#1806] opened 2019-10-11 07:57 UTC
BotBuilder-Samples/samples/javascript_nodejs/15.handling-attachments/

When hosted on Azure, attachment.name containts a prefix ::fromClient. in my case this caused an InternalServerErrror on Azure. Fs actually throws an error that i  cannot find the file. See https://stackoverflow.com/questions/58306146/internal-server-error-om-azure-when-writing-file-from-buffer-to-filesystem
I had to remove the prefix for it to work

## To Reproduce
Host the attachmentbot on Azure (Node)
Upload an attachment.
Crash

**Comment by dmvtech** [comment] 2019-10-14 23:37
I can this as well. Looking into it further.

**Comment by dmvtech** [comment] 2019-10-15 18:12
This seems to be the case for only Test in Web Chat (haven't tested full web chat yet). But does not happen in MS Teams, Telegram or Skype. 

@HesselWellema can you confirm that `Test in Web Chat `is where you are witnessing the behavior. Do you have any other channels that exhibit this behavior?

**Comment by dmvtech** [comment] 2019-10-15 18:17
Additionally, it doesn't have to be hosted in Azure. I have tested with a locally hosted bot and it throws an exception there too. It's just TiWC (at least for now).

**Comment by HesselWellema** [comment] 2019-10-15 18:37
Hi, locally running on Node with bot emulator  I did not witness any issues. Attachment.name does not resolve with a ::fromClient prefix in that case. I did witness the issue it in webchat.

**Comment by dmvtech** [comment] 2019-10-15 18:42
thanks @HesselWellema 

I meant to say that I tested a bot that was in azure, but the endpoint (code) was hosted locally (using ngrok). I didn't test in emulator, but thanks for that info.

I also confirmed iframe webchat is failing. I am testing with full web chat, newer versions. Stand by.

**Comment by dmvtech** [comment] 2019-10-15 19:02
Finding: this is done by the DirectLine service.

**Comment by dmvtech** [comment] 2019-10-15 21:46
Fix is in the pipeline. Should ship this week.

**Comment by dmvtech** [comment] 2019-10-18 22:45
This fix is in place. @HesselWellema can you confirm the same for you?

**Comment by HesselWellema** [comment] 2019-10-19 07:32
Tested in webchat. Works like a charm. Thank you!

**Closed** 2019-10-19 11:17 UTC
Labels: Bot Services, bug, customer-replied-to, customer-reported
