### ISSUE TITLE
401 When Using UserAssignedMSI for 57.teams-conversation-bot

### ISSUE THREAD

**Issue by ryankmcintyre** [microsoft/BotBuilder-Samples#3709] opened 2022-03-09 00:23 UTC
## Sample information
1. Sample type: sample
2. Sample language: dotnetcore
3. Sample name: TeamsConversationBot

## Describe the bug
Following the instructions on the [sample README](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/57.teams-conversation-bot) results in a `401 Unauthorized` error during testing the app in Teams.

## To Reproduce
1. Follow the steps in the README to try the sample and use a User Assigned Managed Identity for the application type when creating the bot.
2. For the `MicrosoftAppId` value in appsettings.json, enter the Client ID value from the Managed Identity.
3. For the `id` and `bots.botId` value in manifest.json, enter the "Microsoft App Id" value from the Azure Bot configuration.

## Expected behavior
The bot should respond in the Teams client without throwing a 401 error.

## Additional context
Here is the stacktrace:
```
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 POST http://localhost:3978/api/messages application/json; charset=utf-8 986
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executing endpoint 'Microsoft.BotBuilderSamples.Controllers.BotController.PostAsync (TeamsConversationBot)'
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Information: Route matched with {action = "Post", controller = "Bot"}. Executing controller action with signature System.Threading.Tasks.Task PostAsync() on controller Microsoft.BotBuilderSamples.Controllers.BotController (TeamsConversationBot).
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Information: Executing action method Microsoft.BotBuilderSamples.Controllers.BotController.PostAsync (TeamsConversationBot) - Validation state: Valid
Microsoft.Bot.Builder.Integration.AspNet.Core.IBotFrameworkHttpAdapter: Information: ProcessActivityAsync
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Information: Executed action method Microsoft.BotBuilderSamples.Controllers.BotController.PostAsync (TeamsConversationBot), returned result Microsoft.AspNetCore.Mvc.EmptyResult in 7.7565ms.
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Information: Executed action Microsoft.BotBuilderSamples.Controllers.BotController.PostAsync (TeamsConversationBot) in 25.615ms
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executed endpoint 'Microsoft.BotBuilderSamples.Controllers.BotController.PostAsync (TeamsConversationBot)'
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 39.2352ms 401 
```

**Comment by anishprasad01** [comment] 2022-03-09 18:06
Hi @ryankmcintyre,

Am I correct in assuming from your stack trace that you are attempting to test your bot locally? If so, this would be why you are encountering issues. 

User-Assigned Manage Identity (UAMI) bots (and applications in general) [cannot be tested locally](https://github.com/Azure/azure-sdk-for-net/issues/19914#issuecomment-810558369). Due to security concerns, the endpoint needed to authenticate UAMI connections will only respond to requests that originate from [within Azure](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview#how-can-i-use-managed-identities-for-azure-resources).

If you wish to test your bot locally, your best bet would be to create a separate `MultiTenant` Azure Bot resource for testing, and reserve your UAMI Azure Bot resource for deploying the bot. It should work fine once the bot is running within Azure.

**Comment by ryankmcintyre** [comment] 2022-03-09 18:59
Thanks @anishprasad01. Considering the sample directs the user to run the bot locally, your assumption is correct. For this sample, and others that direct the user to test locally, I'd highly suggest adding language to direct the user to not use UAMI. Perhaps including the link you shared here. That would save a lot of frustration.

**Comment by anishprasad01** [comment] 2022-03-10 00:59
Thanks for your feedback. I know it's a bit hard to find, but this actually is documented on the [Debugging with ngrok](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-channel-ngrok?view=azure-bot-service-4.0) page in the Bot Framework documentation.

Since this is expected behavior and we've identified a resolution, I'm going to go ahead and close this issue. If you have issues or feature requests in the future, please feel free to raise them in the appropriate repository.

**Closed by anishprasad01** 2022-03-10 00:59 UTC
Labels: customer-reported, Bot Services, customer-replied-to

**Comment by ryankmcintyre** [comment] 2022-03-10 16:02
> I know it's a bit hard to find

Perhaps that statement alone would be enough to get the sample README's updated? Samples should be straightforward and easy to follow, not require digging into unlinked documentation to discover the samples limitations. I wish whoever owned the samples in this repo would reconsider the request.

**Comment by anishprasad01** [comment] 2022-03-10 16:21
Updating the READMEs is planned, but I have no timeline to offer.
