### ISSUE TITLE
Action.ToggleVisibility - Something went wrong. Please try again. 

### ISSUE THREAD

**Issue by ChernHwee** [microsoft/BotBuilder-Samples#3856] opened 2022-12-14 05:00 UTC
## Describe the bug
In the Microsoft teams application when I click the toggle visibility button, it displays as usual but the adaptive card shows
"Something went wrong. Please try again." 
Initially, I suspect it is my code issue but when I ran the example it still shows "Something went wrong. Please try again." 

## To Reproduce
Steps to reproduce the behaviour:
1. Go to https://adaptivecards.io/explorer/Action.ToggleVisibility.html
2. Copy the example JSON
4. Login into Microsoft teams
5. Go to the Developer Portal
6. Click on Design and build Adaptive Cards
7. Create a new card
8. Paste the example JSON
9. Save and Send me this card
10. Click any of the buttons

## Expected behaviour
It should not show "Something went wrong". Please try again

## Screenshots
![image](https://user-images.githubusercontent.com/72246152/207509785-41bc5b18-5b44-4276-bea7-80d05a3c600c.png)

**Comment by stevkan** [comment] 2022-12-15 18:48
Duplicate of https://github.com/microsoft/botframework-sdk/issues/6558.

**Closed by stevkan** 2022-12-15 18:48 UTC
Labels: bug, Bot Services, needs-triage
