### ISSUE TITLE
On Microsoft teams when I click allow permission to download file. I got something went wrong message

### ISSUE THREAD

**Issue by ChernHwee** [microsoft/BotBuilder-Samples#3857] opened 2022-12-15 05:35 UTC
## Describe the bug
On Microsoft teams application. After I followed and ran [56.teams-file-upload](https://github.com/microsoft/BotBuilder-Samples/tree/22fcff680a3e11006eb09b81ac5ed4de345933e2/archive/samples/python/56.teams-file-upload), I have click allowed  and it shows the something went wrong message

## To Reproduce
1. Execute 56.teams-file-upload example
2. type something on the bot
3. Press allow in the upload permission

## Expected behavior
Upon clicking it, it should not show the something went wrong

## Screenshots
![image](https://user-images.githubusercontent.com/72246152/207523122-9fe831c0-8b00-4e81-be67-9a08d6cd4aaa.png)

**Comment by anishprasad01** [comment] 2022-12-15 19:10
Duplicate of https://github.com/microsoft/botframework-sdk/issues/6559

**Closed by anishprasad01** 2022-12-15 19:10 UTC
Labels: bug, customer-reported, Bot Services
