### ISSUE TITLE
app.py crashes with `500 internal server error` and `aiohttp.web_exceptions.HTTPNotFound: Not Found`

### ISSUE THREAD

**Issue by olsgaard** [microsoft/BotBuilder-Samples#3927] opened 2023-11-14 09:44 UTC
## Sample information
1. Sample type: samples
2. Sample language: python
3. Sample name: 02

## Describe the bug
app.py crashes due to `aiohttp.web_exceptions.HTTPNotFound: Not Found`, 

## To Reproduce
```
$ python3 -m venv venv
$ source venv/bin/activate
$ python --version
Python 3.8.18
$ pip install --upgrade pip
$ cd botbuilder-samples/samples/python/02.echo-bot
$ pip install -r requirements.txt
$ python app.py 
======== Running on http://localhost:3978 ========
(Press CTRL+C to quit)
Traceback (most recent call last):
  File "/botbuilder-samples/venv/lib/python3.8/site-packages/botbuilder/core/integration/aiohttp_channel_service_exception_middleware.py", line 20, in aiohttp_error_middleware
    response = await handler(request)
  File "/botbuilder-samples/venv/lib/python3.8/site-packages/aiohttp/web_urldispatcher.py", line 931, in _handle
    raise self._http_exception
aiohttp.web_exceptions.HTTPNotFound: Not Found
Traceback (most recent call last):
  File "/botbuilder-samples/venv/lib/python3.8/site-packages/botbuilder/core/integration/aiohttp_channel_service_exception_middleware.py", line 20, in aiohttp_error_middleware
    response = await handler(request)
  File "/botbuilder-samples/venv/lib/python3.8/site-packages/aiohttp/web_urldispatcher.py", line 931, in _handle
    raise self._http_exception
aiohttp.web_exceptions.HTTPNotFound: Not Found
```
## Expected behavior
an aiohttp server running that won't crash on any and all requests.

**Comment by kevroy314** [comment] 2023-11-14 15:36
Also seeing this - first time trying the samples. Happens using conda with python 3.10 and 3.8.2 (per Readme). Also getting 3 errors on the botbuilder-python unit tests. Not sure if they're related but here's the summary:
```-- Docs: https://docs.pytest.org/en/stable/warnings.html
=============================================== short test summary info ================================================
FAILED libraries/botbuilder-dialogs/tests/test_oauth_prompt.py::OAuthPromptTests::test_should_timeout_oauth_prompt_with_message_activity
FAILED libraries/botbuilder-dialogs/tests/test_oauth_prompt.py::OAuthPromptTests::test_should_timeout_oauth_prompt_with_token_response_event_activity
FAILED libraries/botbuilder-dialogs/tests/test_oauth_prompt.py::OAuthPromptTests::test_should_timeout_oauth_prompt_with_verify_state_operation_activity
ERROR libraries/functional-tests/tests/test_slack_client.py::SlackClient::test_send_and_receive_slack_message - Excep...```

**Comment by kevroy314** [comment] 2023-11-14 18:11
I figured out the issue - you're not meant to interact via direct link to localhost - you're meant to use the bot emulation framework:
![image](https://github.com/microsoft/BotBuilder-Samples/assets/301111/8b69da38-f5ff-4b0d-98fb-733df9a8ffb8)

Click Open Bot and copy in http://localhost:3978/api/messages . Then try the bot.

See https://learn.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-create-bot?view=azure-bot-service-4.0&tabs=python%2Cvs#start-the-emulator-and-connect-your-bot 

Duplicate of this issue: https://github.com/microsoft/BotBuilder-Samples/issues/2368

**Comment by stevkan** [comment] 2023-12-07 01:10
@kevroy314  - Thank you for your input. It is much appreciated. I'm happy you were able to resolve the issue. And, as you already know, yes, you need to use a client to communicate with the bot.

@olsgaard - Was your issue stemming from the same mistake? Are you still having an issue in running the bot?

**Comment by stevkan** [comment] 2024-01-02 20:23
Closing due to inactivity. Please feel free to reopen if the issue persists or you have new details to share.

**Closed by stevkan** 2024-01-02 20:23 UTC
Labels: bug, needs-triage
