### ISSUE TITLE
Can't creat the QnA 

### ISSUE THREAD

**Issue by fhe-fr** [Microsoft/BotBuilder-Samples#1205] opened 2019-02-05 15:04 UTC
## Sample information
1. Sample type: [\samples\ or \solutions\]
samples
2. Sample language: [dotnetcore or webapi or es6 or nodejs or typescript]
nodejs 
3. Sample name: <Name of the sample>
11.qnamaker
## Describe the bug
Give a clear and concise description of what the bug is.
I run the command:
msbot clone services --name "demo-qnamaker1" --code-dir "." --location westus --sdkLanguage "Node" --folder deploymentScripts/msbotClone --verbose
and get  back an error during the KB creation:

Creating QnA Maker KB [qnamaker-QnAMaker]
qnamaker create kb --subscriptionKey 60782c5c0a16434cae9dbd63a95a041f --name "qnamaker-QnAMaker" --in deploymentScripts\msbotClone\34.qna --wait --msbot -q
Command failed: qnamaker create kb --subscriptionKey 60782c5c0a16434cae9dbd63a95a041f --name "qnamaker-QnAMaker" --in deploymentScripts\Failed..              Error: {    "operationState": "Failed",    "createdTimestamp": "2019-02-05T02:56:15Z",    "lastActionTimestamp": "2019-02-05T02:56:17Z",    "userId": "0b151351c8de453b9c56e89dad21f010",    "operationId": "4e1555d9-8217-41fd-9b64-60e217099ee5"}

## To Reproduce
1. Go to 'Download BotBuilder-Samples'
2. Click on ' go to the ...\botbuilder-samples\samples\javascript_nodejs\11.qnamaker and run a dos command and firethe commands in the README.md '

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by mdrichardson** [comment] 2019-02-05 18:30
I'm going to close this as this is more or less a duplicate of https://github.com/Microsoft/BotBuilder-Samples/issues/1187

The solution right now is that if you have a bot that uses QnAMaker, you can't use `msbot clone services...` to create the QnAMaker knowledgebase. You have to create that resource manually. You have two options to replace using `msbot clone services...`

1. Use the `msbot clone services...` command and let it create all resources up until it gets to `qnamaker create kb...`, making sure you create any remaining resources that it missed at the end. 

2. Get a list of the resources you need by running the `msbot clone services...` command. It will list all of the required resources. Then choose "no" so that it doesn't create them and you can go create them manually in Azure.

In either case, for the QnA kb, you have to go to [qnamaker.ai](www.qnamaker.ai) and go through the steps found by clicking "Create a knowledge base".

**Closed by mdrichardson** 2019-02-05 18:30 UTC
