### ISSUE TITLE
Samples (csharp_dotnetcore/adaptive-dialog) the remove item from list is not working

### ISSUE THREAD

**Issue by ceciliaavila** [microsoft/BotBuilder-Samples#3583] opened 2021-11-05 13:24 UTC
## Context
For more information, see the parent issue. #3436

## Sample information
1. Sample type: Samples
2. Sample language: csharp_dotnetcore/adaptive-dialog
3. Sample name: 
   - 06.todo-bot
   - 08.todo-bot-luis-qnamaker

## Describe the bug
These bots create a list of items. Adding the items work ok, but when you want to remove an item from the list is not working.
![image](https://user-images.githubusercontent.com/44245136/140516742-f3703db5-9d5c-467b-bf54-9d94e4be7b39.png)

## Expected behavior
The selected item should be removed from the list.

## Actual behavior
The bot ignores the remove message.

**Comment by sw-joelmut** [comment] 2021-11-08 14:57
Closing this issue, since it could not be reproduced.
Both bots are working as expected when adding and removing items from the list.
![image](https://user-images.githubusercontent.com/62260472/140764604-d2b48481-a9b5-4eda-8bb1-68c2d7ff0cab.png)

**Closed by sw-joelmut** 2021-11-08 14:57 UTC
Labels: bug, P1, ExemptFromDailyDRIReport
