### ISSUE TITLE
[JS]02. Echobot with counter state missing saveChanges

### ISSUE THREAD

**Issue by v-ducvo** [Microsoft/BotBuilder-Samples#396] opened 2018-09-17 18:17 UTC
### SDK Platform

Node SDK

### URL of Code Sample

https://github.com/Microsoft/BotBuilder-Samples/blob/v4/javascript_nodejs/02.echobot-with-counter/dialogs/mainDialog/index.js

### Problem Description
onTurn: after setting the state property, we need to call "saveChanges" … also, when calling to set the state property, it should be called with "await".

**Comment by v-ducvo** [comment] 2018-09-17 18:38
also, the "count" logic is a bit off...if we default "count = 1" then set should be use "count++"...otherwise default "count=0".

**Comment by v-ducvo** [comment] 2018-09-17 18:39
Remove line 73 because we no longer use middleware for state management.

**Comment by stevengum** [comment] 2018-09-25 23:27
#397 was a duplicate of this, and it looks like the issue regarding the count incrementing was fixed. This has been resolved.

**Closed by stevengum** 2018-09-25 23:27 UTC
Labels: bug
