### ISSUE TITLE
CoreBot (adaptive dialogs version) doesn't evaluate triggers correctly

### ISSUE THREAD

**Issue by fabio-muramatsu** [microsoft/BotBuilder-Samples#1911] opened 2019-11-03 02:10 UTC
## Sample information
1. Sample type: \samples\
2. Sample language: dotnetcore
3. Sample name: CoreBot (using adaptive dialogs)

## Describe the bug
Intents with conditions fail to evaluate. 

## To Reproduce
1. Type `Help`
2. Bot replies `Sorry, I do not understand that. Can you try and re-phrase?`

## Expected behavior
Bot should reply with the bot overview

## Additional context
The same happens with the Cancel intent. The greeting intent (which doesn't have any conditions) works as expected.
For the Help intent, I've verified that the bot state should make the bot trigger the Help action:
![image](https://user-images.githubusercontent.com/14302074/68079247-378d9400-fda4-11e9-9515-5937ecb82b8d.png)

[bug]

**Comment by mdrichardson** [comment] 2019-11-04 17:41
@fabio-muramatsu Are you using the latest version of that sample? It was updated 4 days ago. Did you follow the [LUIS Setup instructions](https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/adaptive-dialog/csharp_dotnetcore/04.core-bot#luis-setup)? It looks like you did, but I just want to make sure.

I typed "Help" and it [appropriately displayed](https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/adaptive-dialog/csharp_dotnetcore/04.core-bot/Dialogs/RootDialog.cs#L68) the [BotOverview dialog](https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/adaptive-dialog/csharp_dotnetcore/04.core-bot/Dialogs/RootDialog.lg#L57):

![image](https://user-images.githubusercontent.com/40401643/68143752-f651cd00-fee6-11e9-9091-d26bfb02c0b2.png)

All that being said, this is an experimental sample, so don't expect everything to work just yet.

**Comment by fabio-muramatsu** [comment] 2019-11-05 03:32
Hi @mdrichardson,
Yes, I have set LUIS properly and I'm up to date with master. This is what I see when I interact with the bot:
![image](https://user-images.githubusercontent.com/14302074/68176355-46f21600-ff39-11e9-93ed-55727e2571a1.png)

If I comment out the conditions for Help and Cancel (lines 54 and 65), these triggers are fired as expected:
![image](https://user-images.githubusercontent.com/14302074/68176423-a0f2db80-ff39-11e9-967e-4e3f19a2eb05.png)

I do understand that these features are not ready for production. However, I'm very interested in trying out this new feature as it greatly simplifies the code in our existing application.

**Comment by mdrichardson** [comment] 2019-11-05 16:20
@fabio-muramatsu I can't seem to reproduce this at all. Based on your first post, you're getting the appropriate LUIS response.

What does your .csproj file look like? I couldn't get my sample to work out of the box since we just upgraded to 4.6; I had to change a couple of the package versions. Try this:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App">
      <PrivateAssets Condition="'%(PackageReference.Version)' == ''">all</PrivateAssets>
      <Publish Condition="'%(PackageReference.Version)' == ''">true</Publish>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.1.2" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Bot.Builder.Dialogs.Adaptive" Version="4.6.0-preview2" />
    <PackageReference Include="Microsoft.Bot.Builder.Dialogs.Debugging" Version="4.6.0-preview2" />
    <PackageReference Include="Microsoft.Bot.Builder.Integration.AspNet.Core" Version="4.6.0" />
    <PackageReference Include="Microsoft.Bot.Builder.LanguageGeneration" Version="4.6.0-preview2" />
    <PackageReference Include="Microsoft.Bot.Builder.AI.Luis" Version="4.6.0" />
  </ItemGroup>

</Project>
```

**Comment by fabio-muramatsu** [comment] 2019-11-06 05:25
@mdrichardson My csproj is very similar, but every reference points to 4.6.0-preview2 (exactly as the version in master):

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App">
      <PrivateAssets Condition="'%(PackageReference.Version)' == ''">all</PrivateAssets>
      <Publish Condition="'%(PackageReference.Version)' == ''">true</Publish>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.1.2" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Bot.Builder.Dialogs.Adaptive" Version="4.6.0-preview2" />
    <PackageReference Include="Microsoft.Bot.Builder.Dialogs.Debugging" Version="4.6.0-preview2" />
    <PackageReference Include="Microsoft.Bot.Builder.Integration.AspNet.Core" Version="4.6.0-preview2" />
    <PackageReference Include="Microsoft.Bot.Builder.LanguageGeneration" Version="4.6.0-preview2" />
    <PackageReference Include="Microsoft.Bot.Builder.AI.Luis" Version="4.6.0-preview2" />
  </ItemGroup>

</Project>
```

Some additional information that may be relevant:
* My system language/region is set to pt-br
* I'm running .net core 3
```
> dotnet --version
3.0.100
```

**Comment by mdrichardson** [comment] 2019-11-06 16:59
@fabio-muramatsu I'm going to close this in favor of [this issue](https://github.com/microsoft/botbuilder-dotnet/issues/2927) just to keep things more concise.

**Closed by mdrichardson** 2019-11-06 16:59 UTC
Labels: Bot Services, customer-replied-to, customer-reported
