### ISSUE TITLE
Task Module in Teams not working in IOS Using Bot framework

### ISSUE THREAD

**Issue by Chekrii** [microsoft/BotBuilder-Samples#2371] opened 2020-05-07 08:46 UTC
## Sample information
1. teams-task-module
2.  .net core 
3. Bot Framework V4

## Describe the bug
I am showing the Task module on click on the adaptive card button. It is working fine in the Teams Desktop application and in the android Teams Mobile app but it is not working in the IOS Teams Mobile app.

Task module is not opening in IOS on click on the button.

This is the iframe that I am displaying on Task Module on the button click and a form is showing on the Task module in Android Teams app and Desktop app.

```
<iframe width="850px" height="725px" src="https://forms.office.com/Pages/****" frameborder="0" marginheight="0" marginwidth="0" max-width="100%" sandbox="allow-forms allow-modals allow-orientation-lock allow-popups allow-same-origin allow-scripts" scrolling="no" style="border: none; max-width: 100%; max-height: 100vh" allowfullscreen mozallowfullscreen msallowfullscreen webkitallowfullscreen></iframe>

```
This is the adaptive card I am using
```
{"type":"AdaptiveCard","version":"1.0","body":[{"type":"TextBlock","text":"Click on the below button to open task module","size":"Medium","weight":"Bolder"}],"$schema":"http://adaptivecards.io/schemas/adaptive-card.json","actions":[{"type":"Action.Submit","title":"Open Task Module","data":{"msteams":{"type":"task/fetch"}}}]}
```
## Expected behavior
Task module should open in IOS Teams Mobile app as well

## Additional context
1. Adaptive Cards on Task module are also not working in the IOS Teams app and working fine for Android and Desktop.
2. In Desktop application, it is showing the Microsoft form to fill the details on Task module whereas, in the Android Teams app, It is not showing the Microsoft form. Please find the Screenshot

<img width="199" alt="AndroidTaskModule" src="https://user-images.githubusercontent.com/49824279/81275372-34cf6c80-906f-11ea-997a-1c587095a307.PNG">

**Comment by Chekrii** [comment] 2020-05-11 08:37
Hello All, Any update on this because one of our features is dependent on Task module.

Thanks.

**Comment by cleemullins** [comment] 2020-05-13 18:07
This looks like it needs to be assigned to the Teams folks, as it's in their module. @clearab Can you please assign/transfer this as needed?

**Comment by clearab** [comment] 2020-05-15 18:23
We currently believe there is a regression in the iOS app - the dev team is investigation.

**Comment by clearab** [comment] 2020-05-22 00:10
The fix for this bug has been coded and tested and will be rolling through our deployment rings over the next few weeks.

**Comment by tracyboehrer** [comment] 2020-06-01 18:21
@clearab What is the status on this?

**Comment by clearab** [comment] 2020-06-02 23:21
The fix for this has been deployed, and is rolling through the Teams deployment rings. It should be available as part of the July iOS build. Please contact the Teams developer support team if the issue persists (https://docs.microsoft.com/en-us/microsoftteams/platform/feedback)

**Closed by clearab** 2020-06-02 23:21 UTC
Labels: Bot Services, customer-replied-to, customer-reported

**Comment by Sujit-Gaikwad** [comment] 2020-07-01 11:15
Hi
with update V2.0.15 I able to see it working on my iPhone X. Will it be working for all iPhone devices on which this version is installed?

can you please confirmed once

thanks ,
sujit

**Comment by Rajkumar235216** [comment] 2022-05-16 04:30
Hi,
I am also facing above issue : "Task Module not working using bot framework" in latest teams app (version 4.7 to 4.8.1)on ios mobile devices.
Task module not opening in chatbot using adaptive card button, and it is giving below error:
"msrest.exceptions.DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'".

I am using Python Bot Framework SDK.
