### ISSUE TITLE
Type error when 'npm run' command is used 

### ISSUE THREAD

**Issue by nstejaswini** [Microsoft/BotBuilder-Samples#1188] opened 2019-01-30 11:24 UTC
## Sample information
1. Sample language: nodejs  
2. Sample name: 	21. Luis-with-appinights:

## Describe the bug
TypeError: Cannot read property 'appId' of null 

## To Reproduce
1. Get all the Prerequisites.
2. Run the nmp install command after specifying the path to the sample.
3 Run the az login and az subscription commands.
4 Run the msbot clone command.
-	No information about how to get the path location for the sample in the bot-builder-samples folder.
5: Run the npm start command. It gives error,
-	TypeError: Cannot read property 'appId' of null 
In index.js file.

## Expected behaviour
The sample should work according the readme.

**Comment by mdrichardson** [comment] 2019-01-30 21:59
@nstejaswini 
Regarding your message above step 5: I've added it to my other README PRs.

Regarding the `appId` of null error: I'll add a step in the README to have the user make sure the LUIS `name` in their `.bot` file matches the one in `LUIS_CONFIGURATION` in `index.js`. That being said, the `msbot clone` command prepends the user's `<your-bot-name>` onto the LUIS `name` in the `.bot` file, so that `testBot` would have the `name` property in the `.bot` file be `testBot_luis-with-appinsights-luis`. @Kaiqb I'd consider this a bug if this isn't intended behavior, but I'm guessing that this is intentional.

**Comment by mdrichardson** [comment] 2019-01-30 22:53
Accidental close. @Kaiqb Regarding my last message, that's intentional behavior, isn't it?

**Comment by mdrichardson** [comment] 2019-02-05 22:14
Closing as this is a non-blocking issue that has had PRs merged for a fix. Regarding the intended behavior mentioned above, `.bot` files and `msbot` are both on their way out, so even if the behavior is unintended, it won't likely be addressed.

**Closed by mdrichardson** 2019-02-05 22:14 UTC
Labels: 4.3, Approved, Bug, P1
