### ISSUE TITLE
The scaleoutbot does not work when dialog has an OAuthPrompt. Getting "OAuthPrompt.GetUserToken(): not supported by the current adapter"

### ISSUE THREAD

**Issue by TechyServe** [microsoft/BotBuilder-Samples#1800] opened 2019-10-09 22:24 UTC
## Sample information
1. Sample type: [\samples\ or \solutions\]
2. Sample language: [dotnetcore or webapi or es6 or nodejs or typescript]
3. Sample name: <Name of the sample>

## Describe the bug
Give a clear and concise description of what the bug is.

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Additional context

[bug]

**Comment by jwiley84** [comment] 2019-10-10 16:53
Closing this as a duplicate of [How to add Iconnectorclient to the botframeworkadapter](https://stackoverflow.com/questions/58324239/how-to-add-iconnectorclient-to-the-botframeworkadapter). If it turns out that this is a bug, will reopen this issue.

**Closed by jwiley84** 2019-10-10 16:53 UTC
Labels: Bot Services, customer-reported
