### ISSUE TITLE
CoreBot doesn't respond to user

### ISSUE THREAD

**Issue by Madddog1997** [microsoft/BotBuilder-Samples#1593] opened 2019-06-25 08:48 UTC
Hello, my problem arose when I tried to launch CoreBot, after writing a message to the bot he only responds with "Sorry, something is not right. We need to start over." when I write "Hi" but after that he does't respond. 
I can see Luis Trace only after first response the first only throws exception (which is show under), I tried changing from Luis Recognizer to RegEx in hope something changes but nothing changed.

Microsoft.Bot.Builder.Integration.AspNet.Core.BotFrameworkHttpAdapter:Error: Exception caught : 0.0 is not a number in expression '0.0'
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executed action method Microsoft.BotBuilderSamples.Controllers.BotController.PostAsync (CoreBot), returned result Microsoft.AspNetCore.Mvc.EmptyResult in 395.4498ms.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executed action Microsoft.BotBuilderSamples.Controllers.BotController.PostAsync (CoreBot) in 417.0678ms
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 425.8361ms 200

**Comment by v-kydela** [comment] 2019-06-25 18:12
@Madddog1997 - Let me see if I can help.

1. Are you using the [csharp_dotnetcore CoreBot](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/13.core-bot)?
2. What steps did you take to run the bot?
3. Did you deploy all of the necessary resources like the LUIS app?
4. Is that stack trace from when you're using a LUIS recognizer or from when you switched to Regex?

**Comment by Madddog1997** [comment] 2019-06-25 20:13
1. No I'm using adaptive dialog demo in experimental [(core-bot)](https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/adaptive-dialog/csharp_dotnetcore)
2. I added NuGet packages and then I created LUIS model like the asked and deployed it on local machine from this source (https://botbuilder.myget.org/F/botbuilder-declarative/api/v3/index.json)
3. Yes I did, I get the response from LUIS in Trace as it chooses the right intent but the bot does not respond, I used that model from CognitiveModels in project folder
4. It's from LUIS but the same exception is dropped when using RegEx on first message, I could add another stack trace from when in debugging mode if you want.

**Comment by vishwacsena** [comment] 2019-06-25 21:45
@Madddog1997 - can you add the stack trace?

**Comment by Madddog1997** [comment] 2019-06-26 08:09
at Microsoft.Bot.Builder.Expressions.Parser.ExpressionEngine.ExpressionTransformer.VisitNumericAtom(NumericAtomContext context) in d:\a\1\s\libraries\Microsoft.Bot.Builder.Expressions.Parser\ExpressionEngine.cs:line 166
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.VisitChildren(IRuleNode node)
   at Microsoft.Bot.Builder.Expressions.Parser.ExpressionEngine.ExpressionTransformer.VisitBinaryOpExp(BinaryOpExpContext context) in d:\a\1\s\libraries\Microsoft.Bot.Builder.Expressions.Parser\ExpressionEngine.cs:line 76
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Rules.IntentRule.BuildExpression(IExpressionParser factory) in d:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs.Adaptive\Rules\IntentRule.cs:line 49
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Rules.Rule.GetExpression(IExpressionParser parser) in d:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs.Adaptive\Rules\Rule.cs:line 55
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Selectors.MostSpecificSelector.Initialize(IEnumerable`1 rules, Boolean evaluate) in d:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs.Adaptive\Selectors\MostSpecificSelector.cs:line 29
   at Microsoft.Bot.Builder.Dialogs.Adaptive.AdaptiveDialog.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs.Adaptive\AdaptiveDialog.cs:line 108
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs\DialogContext.cs:line 246
   at Microsoft.Bot.Builder.Dialogs.ComponentDialog.BeginDialogAsync(DialogContext outerDc, Object options, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs\ComponentDialog.cs:line 66
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs\DialogContext.cs:line 246
   at Microsoft.BotBuilderSamples.DialogExtensions.Run(Dialog dialog, ITurnContext turnContext, IStatePropertyAccessor`1 accessor, CancellationToken cancellationToken) in C:\Users\MichalHornak\Downloads\BotBuilder-Samples-master\BotBuilder-Samples-master\experimental\adaptive-dialog\csharp_dotnetcore\04.core-bot\DialogExtensions.cs:line 22
   at Microsoft.BotBuilderSamples.Bots.DialogBot`1.OnMessageActivityAsync(ITurnContext`1 turnContext, CancellationToken cancellationToken) in C:\Users\MichalHornak\Downloads\BotBuilder-Samples-master\BotBuilder-Samples-master\experimental\adaptive-dialog\csharp_dotnetcore\04.core-bot\Bots\DialogBot.cs:line 47
   at Microsoft.BotBuilderSamples.Bots.DialogBot`1.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken) in C:\Users\MichalHornak\Downloads\BotBuilder-Samples-master\BotBuilder-Samples-master\experimental\adaptive-dialog\csharp_dotnetcore\04.core-bot\Bots\DialogBot.cs:line 35
   at Microsoft.Bot.Builder.Dialogs.Debugging.DebugAdapter.Microsoft.Bot.Builder.IMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs.Debugging\DebugAdapter.cs:line 144
   at Microsoft.Bot.Builder.Dialogs.Debugging.DebugAdapter.Microsoft.Bot.Builder.IMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs.Debugging\DebugAdapter.cs:line 152
   at Microsoft.Bot.Builder.RegisterClassMiddleware`1.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder\RegisterClassMiddleware.cs:line 41
   at Microsoft.Bot.Builder.RegisterClassMiddleware`1.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder\RegisterClassMiddleware.cs:line 41
   at Microsoft.Bot.Builder.AutoSaveStateMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder\AutoSaveStateMiddleware.cs:line 60
   at Microsoft.Bot.Builder.RegisterClassMiddleware`1.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder\RegisterClassMiddleware.cs:line 41
   at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder\MiddlewareSet.cs:line 56
   at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder\BotAdapter.cs:line 167

**Comment by Madddog1997** [comment] 2019-06-26 08:11
at Microsoft.Bot.Builder.Expressions.Parser.ExpressionEngine.ExpressionTransformer.VisitNumericAtom(NumericAtomContext context) in d:\a\1\s\libraries\Microsoft.Bot.Builder.Expressions.Parser\ExpressionEngine.cs:line 166
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.VisitChildren(IRuleNode node)
   at Microsoft.Bot.Builder.Expressions.Parser.ExpressionEngine.ExpressionTransformer.VisitBinaryOpExp(BinaryOpExpContext context) in d:\a\1\s\libraries\Microsoft.Bot.Builder.Expressions.Parser\ExpressionEngine.cs:line 76
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Rules.IntentRule.BuildExpression(IExpressionParser factory) in d:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs.Adaptive\Rules\IntentRule.cs:line 49
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Rules.Rule.GetExpression(IExpressionParser parser) in d:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs.Adaptive\Rules\Rule.cs:line 55
   at Microsoft.Bot.Builder.Dialogs.Adaptive.Selectors.MostSpecificSelector.Initialize(IEnumerable`1 rules, Boolean evaluate) in d:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs.Adaptive\Selectors\MostSpecificSelector.cs:line 29
   at Microsoft.Bot.Builder.Dialogs.Adaptive.AdaptiveDialog.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs.Adaptive\AdaptiveDialog.cs:line 108
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs\DialogContext.cs:line 246
   at Microsoft.Bot.Builder.Dialogs.ComponentDialog.BeginDialogAsync(DialogContext outerDc, Object options, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs\ComponentDialog.cs:line 66
   at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs\DialogContext.cs:line 246
   at Microsoft.BotBuilderSamples.DialogExtensions.Run(Dialog dialog, ITurnContext turnContext, IStatePropertyAccessor`1 accessor, CancellationToken cancellationToken) in C:\Users\MichalHornak\Downloads\BotBuilder-Samples-master\BotBuilder-Samples-master\experimental\adaptive-dialog\csharp_dotnetcore\04.core-bot\DialogExtensions.cs:line 22
   at Microsoft.BotBuilderSamples.Bots.DialogBot`1.OnMessageActivityAsync(ITurnContext`1 turnContext, CancellationToken cancellationToken) in C:\Users\MichalHornak\Downloads\BotBuilder-Samples-master\BotBuilder-Samples-master\experimental\adaptive-dialog\csharp_dotnetcore\04.core-bot\Bots\DialogBot.cs:line 47
   at Microsoft.BotBuilderSamples.Bots.DialogBot`1.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken) in C:\Users\MichalHornak\Downloads\BotBuilder-Samples-master\BotBuilder-Samples-master\experimental\adaptive-dialog\csharp_dotnetcore\04.core-bot\Bots\DialogBot.cs:line 35
   at Microsoft.Bot.Builder.Dialogs.Debugging.DebugAdapter.Microsoft.Bot.Builder.IMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs.Debugging\DebugAdapter.cs:line 144
   at Microsoft.Bot.Builder.Dialogs.Debugging.DebugAdapter.Microsoft.Bot.Builder.IMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder.Dialogs.Debugging\DebugAdapter.cs:line 152
   at Microsoft.Bot.Builder.RegisterClassMiddleware`1.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder\RegisterClassMiddleware.cs:line 41
   at Microsoft.Bot.Builder.RegisterClassMiddleware`1.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder\RegisterClassMiddleware.cs:line 41
   at Microsoft.Bot.Builder.AutoSaveStateMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder\AutoSaveStateMiddleware.cs:line 60
   at Microsoft.Bot.Builder.RegisterClassMiddleware`1.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder\RegisterClassMiddleware.cs:line 41
   at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder\MiddlewareSet.cs:line 56
   at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken) in d:\a\1\s\libraries\Microsoft.Bot.Builder\BotAdapter.cs:line 167

**Comment by v-kydela** [comment] 2019-06-28 19:00
@Madddog1997 - Can you post a screenshot of what you're seeing in Emulator? This is what I'm seeing after sending "hi" as the first message:

![image](https://user-images.githubusercontent.com/41968495/60364899-32ef4400-999c-11e9-816f-37945d8e483b.png)

Are you seeing the welcome card for example?

**Comment by Madddog1997** [comment] 2019-06-29 12:22
Here you go.

![Screenshot_2](https://user-images.githubusercontent.com/52194912/60384011-46241180-9a79-11e9-99e1-473ca8c3e066.png)

**Comment by AndreMantas** [comment] 2019-07-10 17:38
Did you update appsettings with luis settings?

something like this

---

Anyway I also got a problem in this bot. The adaptive dialog is not working as expected:

![image](https://user-images.githubusercontent.com/7627975/60990981-89b43080-a341-11e9-8850-ae38c9fbb36d.png)

And, if i type any city name it just assumes I want to cancel:

![image](https://user-images.githubusercontent.com/7627975/60991105-c08a4680-a341-11e9-9092-9fab2df4e506.png)

Sure, LUIS is not helping since it returns Cancel as top scoring intent.

How would we fix this without having to assign lots of answers to the None intent, for example?

**Comment by Madddog1997** [comment] 2019-07-11 09:19
Yes I did, I even tested it with newly downloaded zip file and still, it didn't work.

**Comment by vishwacsena** [comment] 2019-07-16 00:56
Fixed via #1650 

The core of the issue is that LUIS does come back with a low confidence intent recognition for single word utterances as well as for those that are used explicitly to resolve values to entities while in the middle of a multi-turn conversation. 

We continue to discuss this problem across LUIS and Adaptive Dialog teams but in the interim, there are two possible solutions - 

1. Reject low confidence intent classifications. Adaptive dialogs allow you to set a constraint on rules and you could simply reject any intent classification (especially for things like cancel) with a low confidence score. 
2. The more right longer term solution is to break up the language understanding models as one for the root dispatcher and one for each multi-turn dialog that requires entity fulfillment. We are still working through this but [here’s](https://github.com/microsoft/BotBuilder-Samples/tree/vishwac/todo-with-listtype/experimental/adaptive-dialog/declarative/luis-bot) a sample of what that would look like in case you are curious.

**Closed by vishwacsena** 2019-07-16 00:56 UTC
Labels: Adaptive

**Comment by Madddog1997** [comment] 2019-07-16 14:04
But that did not resolve my problem.... 
It still shows up -> Exception caught : 0.0 is not a number in expression '0.0' only now it shows up on connection to Bot and yes I did update to newest commited project and yes I have set up LUIS. 

If I comment that line where rules are added in dialog then it won't show up.

**Comment by v-kydela** [comment] 2019-07-22 21:03
@vishwacsena - Isn't it curious that the exception `0.0 is not a number in expression '0.0'` would be thrown at all? The line number in the stack trace is consistent with ExpressionEngine.cs at this commit: https://github.com/microsoft/botbuilder-dotnet/commit/cac3ed0e68a60f6e177476f50b44fc8aef8f52c9

The method `VisitNumbericAtom` looks like this:

```c#
public override Expression VisitNumericAtom([NotNull] ExpressionParser.NumericAtomContext context)
{
    if (int.TryParse(context.GetText(), out var intValue))
    {
        return Expression.ConstantExpression(intValue);
    }

    if (double.TryParse(context.GetText(), out var doubleValue))
    {
        return Expression.ConstantExpression(doubleValue);
    }

    throw new Exception($"{context.GetText()} is not a number in expression '{context.GetText()}'");
}
```

The exception is only thrown if the text cannot be parsed as an int or a double. Why would "0.0" have any trouble being parsed as a double?
