### ISSUE TITLE
When run botbuilder getting this error on command prompt.

### ISSUE THREAD

**Issue by himmohit** [microsoft/BotBuilder-Samples#2098] opened 2020-01-05 17:46 UTC
![bot error](https://user-images.githubusercontent.com/59510466/71783752-56610e80-3011-11ea-868e-8f134b72ab9b.PNG)

**Comment by mdrichardson** [comment] 2020-01-06 17:35
@himmohit I wasn't able to reproduce this error. Can you try a couple of things:

1. Ensure you ran `npm install -g windows-build-tools` in an elevated PowerShell
2. [Add `%SystemRoot%\System32\Wbem` to your System Environment PATH variable](https://superuser.com/a/1178758)

If that doesn't work, please let me know:

1. Your node version `node -v`
2. Your npm version `npm -v`
3. Your yeoman version `yo --version`
4. Your botbuilder generator version `npm ls -g generator-botbuilder`

**Comment by mdrichardson** [comment] 2020-01-08 18:45
@himmohit Are you still having this issue?

**Comment by himmohit** [comment] 2020-01-12 13:57
Ofcourse, my windows build tools giving me error there...

**Comment by mdrichardson** [comment] 2020-01-13 16:09
@himmohit Unfortunately, Windows Build Tools is required. Installing through PowerShell always worked best for me. Alternatively, you could start by cloning [the samples repo](https://github.com/microsoft/botbuilder-samples) and using one of the samples, instead of using yeoman.

As this appears to be an issue with `windows-build-tools`, I'll close this issue. Feel free to re-open if you feel the issue is indeed with the samples.

**Closed by mdrichardson** 2020-01-13 16:09 UTC
Labels: Bot Services, customer-replied-to, customer-reported

**Comment by himmohit** [comment] 2020-01-15 04:08
I tried that as well but am getting error there.

**Comment by mdrichardson** [comment] 2020-01-15 16:20
@himmohit You may want to [open an issue in the `windows-build-tools` repo](https://github.com/felixrieseberg/windows-build-tools/issues/new)
