### ISSUE TITLE
Suggested actions are not supported by the Teams channel. Please see more information here:

### ISSUE THREAD

**Issue by Shobraj** [microsoft/BotBuilder-Samples#3870] opened 2023-03-03 05:13 UTC
Suggested actions are not supported by the Teams channel. Please see more information here:
https://learn.microsoft.com/en-us/azure/bot-service/bot-service-channels-reference?view=azure-bot-service-4.0#card-action-support-by-channel

_Originally posted by @dmvtech in https://github.com/microsoft/BotBuilder-Samples/issues/3868#issuecomment-1452258840_

**Comment by dmvtech** [comment] 2023-03-08 18:20
Closing as duplicate of linked issue.

**Closed by dmvtech** 2023-03-08 18:20 UTC
