### ISSUE TITLE
Bot Builder application on .Net Core 2

### ISSUE THREAD

**Issue by akontsevich** [Microsoft/BotBuilder-Samples#182] opened 2017-09-02 00:30 UTC
Seems we now able to build and run Bot framework on .Net Core 2. Good to add some examples or instructions, or even application generators how to make bot application there. What steps to do after `dotnet new webapi -o EchoBot` command and adding Nuget packages references `Microsoft.Bot.Builder` and `System.IdentityModel.Tokens.Jwt`?

[This example](https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Samples/Microsoft.Bot.Sample.AspNetCore.Echo) seems outdated.

**Comment by JasonSowers** [comment] 2017-09-04 15:50
Closing as duplicate of https://github.com/Microsoft/BotBuilder/issues/3412 please do not double post

**Closed by JasonSowers** 2017-09-04 15:50 UTC

**Comment by akontsevich** [comment] 2017-09-04 15:52
> Closing as duplicate of Microsoft/BotBuilder#3412 please do not double post

Just wasn't sure about correct project to address.

**Comment by JasonSowers** [comment] 2017-09-04 15:55
No problem, but there is already a discussion on the other issue, so let's keep that one going.
