### ISSUE TITLE
LuisAction properties are null upon receiving a message in LuisActionMissingEntitiesDialog

### ISSUE THREAD

**Issue by kieranwarrington** [Microsoft/BotBuilder-Samples#278] opened 2018-07-04 09:25 UTC
### SDK Platform
.NET

### Problem Description
Using a class (Child) inherited from an instantiation of BaseLuisAction (Parent), upon response to the second required property, the values of each field on the ILuisAction luisAction of the LuisActionMissingEntitiesDialog are all null.
This means the IsValid will never be able to return true.

![image](https://user-images.githubusercontent.com/22681829/42268858-2cb9764e-7faf-11e8-8539-92b5700c2580.png)

![image](https://user-images.githubusercontent.com/22681829/42268691-bc7c55c2-7fae-11e8-8990-35a000f3187b.png)

```
    [LuisActionBinding("Child")]
    public class ChildAction : ParentAction
    {
        public async Task Process(IDialogContext context)
        {
            await context.PostAsync($"Child {Foo} {Bar}");
        }
    }
```

```
[LuisActionBinding("Parent")]
    public class ParentAction : BaseLuisAction
    {
        [Required(ErrorMessage = "Foo is required")]
        public string Foo { get; set; }

        [Required(ErrorMessage = "Bar is required")]
        public string Bar { get; set; }

        public async override Task<object> FulfillAsync()
        {
            return this;
        }

        public async Task Process(IDialogContext context)
        {
            await context.PostAsync($"Parent {Foo} {Bar}");
        }
    }
```

**Comment by Zerryth** [comment] 2018-07-09 23:13
@kieranwarrington thanks for reaching out!

I'm unable to reproduce the bug you are encountering properly, given only these 2 code snippets.

Could you please provide a link to this project on GitHub? Happy to dive into the matter further, afterwards :)

**Comment by Zerryth** [comment] 2018-08-01 22:48
Closing due to user unresponsiveness

**Closed by Zerryth** 2018-08-01 22:48 UTC
