### ISSUE TITLE
Declarative bot errors out on start up when published to azure

### ISSUE THREAD

**Issue by TechyServe** [microsoft/BotBuilder-Samples#1581] opened 2019-06-17 14:08 UTC
Getting the following error on start up 

 [Critical] Microsoft.AspNetCore.Hosting.Internal.WebHost: Application startup exception
System.ArgumentNullException: Value cannot be null.
Parameter name: projectFile
  at Microsoft.Bot.Builder.Dialogs.Declarative.Resources.ResourceExplorer.LoadProject(String projectFile, String[] ignoreFolders, Boolean monitorChanges)
  at Dara.Bot.Startup.ConfigureServices(IServiceCollection services) in C:\projects\Dara\src\Bot\Dara.Bot\Startup.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
  at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
  at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

**Comment by stevkan** [comment] 2019-06-17 19:33
Adaptive Dialogs are still in preview. As such, the required dependencies are not supported in Azure for general consumption. For this to work, you will need to register and include the dependencies manually so your project will work someplace other than on you local machine.

Closing this as resolved. If you have additional questions related to this, please feel free to re-open the issue.

**Closed by stevkan** 2019-06-17 19:33 UTC

**Comment by EricDahlvang** [comment] 2019-06-18 01:19
@TechyServe I think you could add a Nuget.config to the solution and provide the package source for myget: https://docs.microsoft.com/en-us/azure/dev-spaces/how-to/use-custom-nuget-feed  This should enable Azure to download the packages from the correct nuget server.

**Comment by GewoonMaarten** [comment] 2019-07-30 09:52
@stevkan This makes no sense to me. When I use the publish function in Visual Studio it builds all the dll's locally, includes the dll's of the dependencies and then uploads them to Azure, right? So why would this error be caused by Azure not knowing the dependencies?

I also tried @EricDahlvang suggestion to include a nuget.config file, but I had no luck. Here is my nuget.config file:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageRestore>
    <!-- Allow NuGet to download missing packages -->
    <add key="enabled" value="True" />
    <!-- Automatically check for missing packages during build in Visual Studio -->
    <add key="automatic" value="True" />
  </packageRestore>
  <packageSources>
    <add key="NuGet official package source" value="https://api.nuget.org/v3/index.json" />
    <add key="botbuilder preview" value="https://botbuilder.myget.org/F/botbuilder-declarative/api/v3/index.json" />
  </packageSources>
</configuration>
```
