### ISSUE TITLE
createkb command failure

### ISSUE THREAD

**Issue by nstejaswini** [Microsoft/BotBuilder-Samples#1187] opened 2019-01-30 11:18 UTC
## Sample information
1. Sample language: nodejs  
2. Sample name: 11.qnamaker

## Describe the bug
Command failed: qnamaker create kb --subscriptionKey e7ed684147004f5b924e3348726a3846 --name "qnamaker-QnAMaker" --in deFailed..              Error: {    "operationState": "Failed",    "createdTimestamp": "2019-01-28T09:55:27Z",    "lastActionTimestamp": "2019-01-28T09:55:28Z",    "userId": "91bbd3223eac4a56b14edf858ff1dfc1",    "operationId": "f51a5145-0408-488a-8125-d6dbd472c095"}

## To Reproduce
1. Get all the Prerequisites.
2: Run the nmp install command after specifying the path to the sample.
3: Run the az login and az subscription commands.
4: Run the msbot clone command. 
    - While Creating the QnA Maker KB an error occurs,

## Expected behaviour
The sample should work according the readme.

**Comment by mdrichardson** [comment] 2019-01-30 21:17
What console were you using? Did you use the `--verbose` flag in the `msbot clone` command? Can you screenshot the error? I got one as well, but not the one you have there.

**Comment by Zerryth** [comment] 2019-01-30 22:49
I think QnA Maker services did push new bits that broke the `qnamaker create kb...` command.

Both JJ and I tried running the qnamaker node sample, and it failed on that command specifically

**Comment by mdrichardson** [comment] 2019-01-30 22:50
I've run it a few times now and the first and last errors were `stderr maxbuffer length exceeded`. The rest have been `invalid subscription key` which is odd, since I don't specify it in the `msbot clone` command and all the other service creations use the appropriate service. 

If I run the `qnamaker create` command manually, outside of the `msbot clone` command, it sort of works....

So, during the `stderr maxbuffer length exceeded` errors, it seems to just time out, which *might* be because when running these manually:

`qnamaker create kb --subscriptionKey <subKey> --name "qnamaker-QnAMaker" --in deploymentScripts\msbotClone\34.qna --wait --msbot -q`

I get the error:

`Error: ENOENT: no such file or directory, stat 'C:\Users\v-micric\Documents\Code\Samples\Test Samples\11.qnamaker\deploymentScriptsmsbotClone34.qna'`

But when I throw `""` around the `--in` path, it works fine. Does it need this for `msbot clone`? Or is this something else?

**Comment by mdrichardson** [comment] 2019-01-31 03:46
Definitely seems to be an issue with subscription keys:

`Access denied due to invalid subscription key. Make sure you are subscribed to an API you are trying to call and provide the right key.`

I've verified that the key that gets passed into `qnamaker create` is the same as the one in my Cognitive Service in Azure. I'll do some more digging into this tomorrow.

**Comment by mdrichardson** [comment] 2019-02-01 00:32
I've now run either `msbot clone` or `qnamaker create` over a dozen times and had maybe 2 or 3 successes. Still trying to pinpoint what's causing the failures.

**Comment by mdrichardson** [comment] 2019-02-04 23:57
Just as an update:

I've been using a PowerShell script to test this that builds the appropriate services with AZ CLI. It then uses qnamaker to hit the API and create the knowledgebase. Making no changes to the script, I have about a 30% success rate of creating a knowledgebase. The others either return a nondescript "failed" error or "Invalid subscription key" error. Again, my Powershell script attempts the exact same process each time (just with different AZ group or resource names) and it fails 70% of the time.

I've reached out to QnAMaker support via email and hoping we get somewhere with this, but the issue isn't with a sample. It's either with AZ CLI (inconsistently creating resources) or QnAMaker API (QnAMaker support has said "there are no known issues with create APIs", but I don't know what else it would be). Still working through this.

**Comment by mdrichardson** [comment] 2019-02-05 01:05
If you want to test this a dozen times like I did, `msbot clone services` is fine, but it takes significantly longer while it creates the 2-3 Azure resources for the bot deployment. You still get the same errors either way, but my Powershell script removes the extra resource creations.  Here's my script if you want to use it:

```powershell
$COG_NAME=<appName>
$AZ_SUBSCRIPTION=<azureSubscriptionKey>
$QNA_ENDPOINT="https://$COG_NAME.azurewebsites.net/"
$AZ_GROUP=<azureGroupName>

$PATH=<pathToQnaFile>
# "C:\Users\v-micric\Documents\Code\Samples\Test Samples\11.qnamaker\deploymentScripts\msbotClone\34.qna"

Write-Host "Creating Search Service"
az search service create -g $AZ_GROUP -n $COG_NAME"-search" --location westus --sku Standard --subscription $AZ_SUBSCRIPTION

Write-Host "Getting Search Keys"
$RESULT=az search admin-key show -g $AZ_GROUP --service-name $COG_NAME"-search" --subscription $AZ_SUBSCRIPTION | ConvertFrom-Json

$KEY=$RESULT.primaryKey

Write-Host "Key: $KEY"

Write-Host "Creating App Service"
az appservice plan create -g  $AZ_GROUP --sku S1 --name $COG_NAME --subscription $AZ_SUBSCRIPTION

Write-Host "Creating WebApp"
az webapp create -g $AZ_GROUP -n $COG_NAME --plan $COG_NAME --subscription $AZ_SUBSCRIPTION
az webapp create -g $AZ_GROUP -n $COG_NAME --plan $COG_NAME --subscription $AZ_SUBSCRIPTION

Write-Host "Setting WebApp Settings"
az webapp config appsettings set -g $AZ_GROUP -n $COG_NAME --subscription $AZ_SUBSCRIPTION --settings \
    AzureSearchName=$COG_NAME"-search" \
    AzureSearchAdminKey=$KEY \
    PrimaryEndpointKey=$COG_NAME"-PrimaryEndpointKey" \
    SecondaryEndpointKey=$COG_NAME"-SecondaryEndpointKey" \
    DefaultAnswer="No good match found in KB." \
    QNAMAKER_EXTENSION_VERSION="latest"

Write-Host "Configuring CORS"
az webapp cors add -g $AZ_GROUP -n $COG_NAME -a "*" --subscription $AZ_SUBSCRIPTION

Write-Host "Creating Cog Service"
az cognitiveservices account create --kind QnAMaker --resource-group $AZ_GROUP -n $COG_NAME --sku S0 --subscription $AZ_SUBSCRIPTION --location westus --yes --api-properties qnaRuntimeEndpoint=$QNA_ENDPOINT --verbose

Write-Host "Sleeping"
Start-Sleep -s 60
# You can probably remove this, but I put it in to make sure resources fully deployed. Didn't help, I don't think

Write-Host "Getting Cog Service Keys"
$RESULT=az cognitiveservices account keys list -g ${AZ_GROUP} -n $COG_NAME --subscription $AZ_SUBSCRIPTION | ConvertFrom-Json
$KEY=$RESULT.key1

Write-Host "Key: $KEY"

Write-Host "Creating KB"
qnamaker create kb --subscriptionKey $KEY --name vmicricTEST --in $PATH --wait True --msbot --debug
```

To write this, I basically grabbed the commands from `msbot` and made it easier to change test variables. There's a couple of arguments changed here and there while testing, but the key thing is that 30% of the time this script works and 70% it fails.

**Comment by mdrichardson** [comment] 2019-02-07 00:55
@rokulka Please post any updates to your investigation of this issue here.

**Comment by rokulka** [comment] 2019-02-07 16:08
**Problem:**
- On creating QnAMaker Cognitive Service Resource,  the QnAMaker backed receives a notification, it in-turn does some updates to set EndpointKeys at the client's WebApp.
- Create KB is called immediately after creating QnAMaker Cognitive Service resource, it fails because the backed updates are not complete yet.
- This issue does not appear via the QnAMaker portal as by the time the user manually creates the KB, the backed updates are complete.

**Fix:**

The solution would be to use 'sleep' after the Cognitive Service resource is created , thus allowing the backend updates to complete (60s should be more than enough)

@sgellock @Zerryth - Please let me know your comments.

@mdrichardson  Thanks for the powershell script, I was able to run it with the with the sleep command. The 'invalid subscription key' error seems to be popping up for the same reason that the Cognitive Services APIM is not initialized yet. Adding a 'sleep' should help with that. Please check your email for the exact script.

**Comment by mdrichardson** [comment] 2019-02-07 18:52
@rokulka 

Agreed. I tested again today and 9/10 of my tests passed when using a 60 second "sleep". The only one that failed produced:

```
Error: {
    "operationState": "Failed",
    "createdTimestamp": "2019-02-07T05:58:59Z",
    "lastActionTimestamp": "2019-02-07T05:59:18Z",
    "userId": "5de37fed8c014d3fb2f5c2ea490d4daa",
    "operationId": "d8e32322-2755-4fcf-b10d-134c45a93e07",
    "errorResponse": {
        "error": {
            "code": "QnaRuntimeError",
            "message": "Runtime error.",
            "innerError": {
                "message": "Authorization Failed",
                "code": "Unauthorized"
            }
        }
    }
}
```

I've opened an issue in the botbuilder-tools repo here: https://github.com/Microsoft/botbuilder-tools/issues/958

Since we've confirmed this is not an issue with a sample, I'm going to close the issue here and it can be continued there.

**Closed by mdrichardson** 2019-02-07 18:52 UTC
Labels: Support
