### ISSUE TITLE
Sample 24 fails to run in emulator

### ISSUE THREAD

**Issue by saikumaru** [microsoft/BotBuilder-Samples#1709] opened 2019-08-19 09:00 UTC
## Sample information
1. Sample type: Samples
2. Sample language: dotnetcore
3. Sample name: 24.bot-authentication-msgraph

## Describe the bug
I have run the bot as per the steps defined in the documentation
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv1%2Ccsharp%2Cbot-oauth

And when tested in emulator, gives the below exception message

> CompactToken parsing failed with error code: 80049217 botframework

## To Reproduce
1. Add in the microsoft appid, password and connection name to settings
2. Start the emulator and provide the app id and password
3. Run through the dialogues
4. Click on "Sign In" prompt
5. Type "me" and wait for the result

## Expected behavior
The bot is expected to show the users name

## Additional context
I have tried the version microsoft-graph-client V1.4 and v1.17, but both failed

[bug]

**Comment by tdurnford** [comment] 2019-08-19 14:47
@tonyanziano Thoughts?

**Comment by jwiley84** [comment] 2019-08-19 15:35
Can you test your connection in the azure portal, to make sure it's valid?

**Comment by saikumaru** [comment] 2019-08-20 13:47
Hi, this actually works now. After reading through another issue I tried all of the suggestions.
https://github.com/microsoft/BotBuilder-Samples/issues/1655


The thing I was missing was to enable the Ngrok setting on emulator.
Please can you add this step to the above samples document to avoid further confusion.

Thank you

**Comment by textminer** [comment] 2019-08-20 14:44
Does anybody know why on the Emulator the token received is compact like: 45024ae0-c357-11e9-8e41-8dd225c566e7|livechat, which then throws the 80049217 exception, but running it on Azure it gets a proper Bearer Token that works?

**Comment by saikumaru** [comment] 2019-08-20 15:03
>Does anybody know why on the Emulator the token received is compact like: 45024ae0-c357-11e9-8e41-8dd225c566e7|livechat, which then throws the 80049217 exception, but running it on Azure it gets a proper Bearer Token that works?

This is exactly what happened in my case too

**Comment by stevkan** [comment] 2019-08-20 18:05
@saikumaru, @textminer, there was an issue filed regarding the "|livechat" exception (issue [#1544](https://github.com/microsoft/BotFramework-Emulator/issues/1544)) in the Botbuilder-Emulator repo. I would suggest you add your comments to that thread so it registers as a customer issue and, thus, will have higher priority.

In either of your cases, are you changing the AAD connection name in your bot after opening Emulator?

**Comment by textminer** [comment] 2019-08-20 18:10
I only change it on the system doing:
        this.oauthPrompt = new OAuthPrompt(LOGIN_PROMPT,
            {
                connectionName: process.env.OAUTH_CARDS_CONNECTION_STRING,
                text: 'Please login into SharePoint',
                title: 'Login',
                timeout: 10000
            });
then, it appears in the Bot Emulator as I redefined it:

![imagen](https://user-images.githubusercontent.com/38899601/63372440-7e025380-c35c-11e9-874a-0bd209887b15.png)

**Comment by stevkan** [comment] 2019-08-20 18:40
@textminer, the "oauth://" bit in your value suggests ngrok is not spinning up correctly for you. When ngrok fails to spin up Emulator falls back to an emulated token flow (i.e. it is not actually connecting to the Azure Bot Service for token generation).

I would suggest you double check your ngrok settings to verify everything is correctly assigned. Do you see anything in the either of the "activity" windows in Emulator (primarily the bottom) displaying any errors?

In this image, ngrok has been configured and Emulator reports as much:
![image](https://user-images.githubusercontent.com/18403946/63374640-1558ae00-c33f-11e9-8263-1e1099a6ca54.png)

**Comment by textminer** [comment] 2019-08-20 19:34
Yes, I see the process running and that is listening:
![imagen](https://user-images.githubusercontent.com/38899601/63378272-44cfe080-c368-11e9-97f6-7a95a891061c.png)

I'm using latest ngrok version 2.3.34

**Comment by stevkan** [comment] 2019-08-29 21:10
How are you connecting your bot when you run it locally? Are you using ngrok, separate from ngrok running in Emulator, to connect your bot to ABS (i.e. changing the messaging endpoint in your bot settings in Azure)? Is the AppId and AppPassword matching between your bot and Emulator?

Just trying to rule out possible scenarios.

**Comment by textminer** [comment] 2019-09-03 14:56
Hi @stevkan, latest build provided of the Bot Emulator that includes more logging showed me that there was an authentication issue. The root cause was that the .bot file with credentials used by the Emulator was from previous versions and as soon as I recreated it the problem was solved.
Thanks

**Comment by stevkan** [comment] 2019-09-03 22:33
Glad you were able to find the cause! Closing this issue as resolved.

**Closed by stevkan** 2019-09-03 22:33 UTC
Labels: Bot Services, customer-replied-to, customer-reported

**Comment by lobigm** [comment] 2019-10-15 13:12
i had the same problem with different solution, for me i had to configure ngrok correctly and (close and open bot Framework  emulator), https://github.com/microsoft/BotFramework-Emulator/issues/1597 

the problem was that the token, it was malformed.
