### ISSUE TITLE
error code: 401

### ISSUE THREAD

**Issue by ncastagno-tgv** [microsoft/BotBuilder-Samples#3461] opened 2021-08-30 16:17 UTC
## Sample information
1. Sample type: samples
2. Sample language: nodejs
3. Sample name: 17. Multilingual Bot

## Describe the bug
when I say "Hi" and then choose language "Español" I get an error:

**[onTurnError] unhandled error: Error: Call to translation services failed**

## To Reproduce
1. Open Bot in Bot Framework Emulator
2. The bot says "This bot will introduce you to translation middleware. Say ‘hi’ to get started."
3. I reply "Hi"
4. The bot says "Choose your language:"
5. I click on "Español"
6. I see "The bot encountered an error or bug"

## Settings.
In the .env file I set the **translatorKey** to the value Key 1 of my BOT-AMS-Translate resource (see attached screenshot) 
![Key 1](https://user-images.githubusercontent.com/62354561/131370805-4d1ba0f9-c117-45ae-a7e8-9275d8b57068.jpg)

## Additional context
I added two console.log display and I can see this values:
        **console.log(res.headers);**
        **console.log(await res.json());** 
```
Headers {
  [Symbol(map)]: [Object: null prototype] {
    'content-type': [ 'text/plain; charset=utf-8' ],
    'x-requestid': [ 'TRAN.SN3P.33F0.0830T1557.B2DCCBF' ],
    'access-control-expose-headers': [ 'X-RequestId' ],
    'x-content-type-options': [ 'nosniff' ],
    'strict-transport-security': [ 'max-age=31536000; includeSubDomains' ],        
    date: [ 'Mon, 30 Aug 2021 15:57:20 GMT' ],
    connection: [ 'close' ],
    'content-length': [ '111' ]
  }
}
```

```
{
  error: {
    code: 401000,
    message: 'The request is not authorized because credentials are missing or invalid.'
  }
}
```

**Comment by dmvtech** [comment] 2021-08-31 20:04
Hi @ncastagno-tgv I can reproduce. Let me investigate.

**Comment by dmvtech** [comment] 2021-08-31 22:18
@ncastagno-tgv This is due to the region of the translation resource in Azure.

If your resource is a global region; this will not fail. As you (and I) were using translation resources in a _specific region_, this needs to be supplied.

You can fix this by adding `Ocp-Apim-Subscription-Region` (with appropriate region) in microsoftTranslator.js file:
```javascript
headers: {
    'Content-Type': 'application/json',
    'Ocp-Apim-Subscription-Key': this.key,
    'Ocp-Apim-Subscription-Region': 'westus2'
}
```

I'll check to see if we can get this sample changed to be more dynamic and avoid this issue.

**Comment by dmvtech** [comment] 2021-09-03 21:15
Closing this as I'm sure this is the issue. If that doesn't resolve for you, please comment. I will address the samples at a later time.

**Closed by dmvtech** 2021-09-03 21:15 UTC
Labels: bug, customer-reported, Bot Services, customer-replied-to
