### ISSUE TITLE
V3 VSIX Generated Bot does not work when deployed to Azure

### ISSUE THREAD

**Issue by sgellock** [Microsoft/BotBuilder-Samples#669] opened 2018-10-10 15:54 UTC
## Sample information
1. v3 VSIX template

## Describe the bug
The v3 VSIX needs to verify that it runs upon deployment.  Customer is raising an issue that state management is in error and is suggesting the generated code needs to reference changes described in: https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-state?view=azure-bot-service-3.0

## To Reproduce
1. With VS2017, install the V3 VSIX
2. Create a new project
3. Deploy the project
4. Connect WebChat up and attempt to talk to the newly deployed bot

## Expected behavior
Bot communicates as expected

[bug]

**Comment by EricDahlvang** [comment] 2018-11-29 21:48
The template does in fact implement the InMemoryDataStore and has comments referencing BotBuilder-Azure in Global.asax.cs : https://github.com/Microsoft/BotBuilder-V3/blob/master/CSharp/Generator/BotApplication/Global.asax.cs

---

- Installed the v3 .vsix from https://github.com/Microsoft/BotBuilder-V3/raw/master/CSharp/Generator/BotBuilderVSIX.vsix 

- Created bot locally, added MicrosoftAppId and MicrosoftAppPassword from an existing Bot Channel registration to the web.config and published to Azure

- Changed the Bot Channel Registration's messaging endpoint to the path of the deployed bot 

- Tested in registration's WebChat, without exception


----
Closing this issue, since I am not able to reproduce the bug.

**Closed by EricDahlvang** 2018-11-29 21:48 UTC
Labels: 4.2, Approved, Bug, P0, Support
