### ISSUE TITLE
Facebook HTTP 405 with Active Learning dialog

### ISSUE THREAD

**Issue by Avalaxy** [microsoft/BotBuilder-Samples#1531] opened 2019-05-22 22:56 UTC
## Sample information
1. Sample type: Samples
2. Sample language: Dotnetcore
3. Sample name: Active Learning https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/qnamaker-activelearning/csharp_dotnetcore

## Describe the bug
I implemented the Active Learning dialog in the Enterprise Bot Template. I did this by starting the Active Learning dialog from the MainDialog whenever a QnA question is found. This works completely fine in the emulator and in the Azure Portal webchat. However, whenever I publish the code and try it on Facebook, the bot returns an error. I can see in Application Insights that an attempt is being made to perform a GET request against https://mybot.azurewebsites.net/api/messages. This results in an HTTP 405 error (method not allowed). I think this is because a POST request should be done instead.

The weird thing is, everything is working fine for the rest of the bot. The dispatcher works fine, the QnAmaker works fine. The only area where I encounter this issue is in the Active Learning dialog. And strangely only on facebook. Does anyone know why this is?

## To Reproduce
1. Get a new copy of the Enterprise Bot Template: https://github.com/microsoft/botframework-solutions/tree/master/templates/Enterprise-Template.
2. Implement the code from the Active Learning sample in the MainDialog, like this: `await dc.BeginDialogAsync(_activeLearningDialogHelper.ActiveLearningDialogName, _qnaOptions, cancellationToken);`.
3. Publish the bot to facebook.
4. Enjoy.

## Code
This is how I hooked up the Active Learning dialog inside my MainDialog:

`await dc.BeginDialogAsync(_activeLearningDialogHelper.ActiveLearningDialogName, _qnaOptions, cancellationToken);`

Other than that, everything is unmodified.

**Comment by tdurnford** [comment] 2019-05-24 15:45
Closing as this appears to be a duplicate of https://github.com/microsoft/botframework-solutions/issues/1411

**Closed by tdurnford** 2019-05-24 15:45 UTC
