### ISSUE TITLE
Task modules not working in ms teams

### ISSUE THREAD

**Issue by harkiratsaluja** [microsoft/BotBuilder-Samples#3695] opened 2022-02-10 07:24 UTC
## Sample information
1. Sample type: Samples
2. Sample language: nodejs
3. Sample name: 54. teams-task-module

## Describe the bug
The task module is not opening on interaction with the button inside ms teams.

## To Reproduce
1. Cloned the repo
2. Navigated to folder 54. teams-task-module
3. Did npm install
4. Updated .env file and manifest json with app ids
5. Created a zip and installed the app into ms teams.
6. Sent a message after installation and bot replied with hero card and adaptive card.
7. Tried pressing any one of the buttons in either of the above cards and nothing happens in desktop app. 
8. Tried checking in web app for console errors and got 2 error messages. One interacting with the button for the first time got the error `TaskModuleLaunchService: launchTaskModuleByInvoke failed: "could not find app definition for app e4ac1f5d-26e0-49e4-ad35-e9db5081035d"` and in subsequent interactions this error `Error: Extension already rendered, only one extension command request can be processed at a time.`

## Expected behavior
Task Module modal should work open and functions `handleTeamsTaskModuleFetch` and `handleTeamsTaskModuleSubmit` should get fired.

**Comment by stevkan** [comment] 2022-02-15 20:45
@harkiratsaluja, thank you for this information. I'm attempting a repro and will respond when I know more.

**Comment by stevkan** [comment] 2022-02-16 22:06
@harkiratsaluja, I was able to repro the issue. And, while a colleague and I tried every which way to get the sample to work or discover a workaround, we were simply unable to do so. Debugging every step has shown that all the appropriate values are being generated, and they match expected values as described in the task module docs regarding the [TaskInfo object](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/invoking-task-modules#the-taskinfo-object) and [Using Task Modules in Bots](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/task-modules/task-modules-bots?tabs=nodejs). I looked at values by debugging the app as well as network requests/responses.

It's worth noting that the code used for generating a task module in the sample was pulled almost line for line from the Teams JS docs/sample demonstrating the same. Lastly, we looked at the bot's Teams manifest and the Azure bot registration and app service. Nothing looked unusual though we did try altering some aspects to be sure, though doing so didn't alter the results.

As a comparison, we also ran the same dotnet sample and ended with the same results. At this point, I believe that either something is blocking the `handleTeamsTaskModuleSubmit` activity handler or how it functions / handles external resources (URLs, for example). If there was a change, then the docs have not been updated to reflect this.

@clearab, do you have any thoughts on this? This feels like it's an issue in the Teams SDK since this can be repro'd in two SDKs. If you agree, could you get this in front of Teams for their consideration?

**Comment by clearab** [comment] 2022-02-16 22:18
I've escalated to Teams internally, seems like there is some issue propagating the app definition appropriately for some reason.

**Comment by clearab** [comment] 2022-02-18 18:23
The Teams support group was able to repro this issue, and has raised a bug internally. I will follow up with more details as they are available.

**Comment by mrivera-ms** [comment] 2022-03-04 19:11
Are there any updates on this, @clearab ?

**Comment by clearab** [comment] 2022-03-04 19:21
It has been assigned to an engineer in Teams, no update on timeline for a fix yet.

**Comment by harkiratsaluja** [comment] 2022-03-11 14:48
We are seeing this issue randomly on few of the adaptive cards.

**Comment by harkiratsaluja** [comment] 2022-03-28 14:52
Hi, is there any update on this? This is blocking our release process.

**Comment by harkiratsaluja** [comment] 2022-05-04 06:20
Hi, is there any update on this? This is blocking our release process.

**Comment by harkiratsaluja** [comment] 2022-06-09 15:14
Hi, are there any updates on this? This is now impacting our customers randomly @clearab. It will really help if you can share some information on the same!.

**Comment by v-chetsh** [comment] 2022-06-10 04:59
@harkiratsaluja - We will check on the bug status and let you know the updates.

**Comment by sayali-MSFT** [comment] 2022-06-10 07:04
@harkiratsaluja - Issue is resolved. Cloned the repo.
Microsoft Teams Version 1.5.00.15719 (64-bit)-E. 
Could you please check it once and let us know?
Ref Doc-https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/54.teams-task-module

**Comment by sayali-MSFT** [comment] 2022-06-14 13:21
@harkiratsaluja -We will inform the internal team ,Let you know once we get any update.

**Comment by sayali-MSFT** [comment] 2022-06-17 14:13
@harkiratsaluja - Currently we don’t have ETA or Update on this thread. 
We will update this thread once the bug is fixed.

**Comment by sayali-MSFT** [comment] 2022-06-22 05:22
@harkiratsaluja -Could you please provide teams details in which Ring you have tested?

**Comment by harkiratsaluja** [comment] 2022-06-22 07:43
@sayali-MSFT thank you for the reply. This issue is being faced by one of our customers. If you can share the exact details which are needed from our end, we can communicate them accordingly and get back to you with the same!

**Comment by sayali-MSFT** [comment] 2022-06-22 07:47
@harkiratsaluja -Please share the Microsoft teams version and please let us know testing environment which is Public Ring or developer preview?

**Comment by harkiratsaluja** [comment] 2022-06-22 08:04
@sayali-MSFT the Microsoft teams version is 1.5.00.15861 and this is the public ring application that is available on ms teams at [Rattle](https://teams.microsoft.com/l/app/bacd48e3-a2e1-48db-992f-609eb58ac326?source=app-details-dialog)

**Comment by sayali-MSFT** [comment] 2022-06-23 05:00
@harkiratsaluja - There is latest update for teams. Could you please update and check with latest version? Are all the users on same teams version?
 Thanks!

**Comment by harkiratsaluja** [comment] 2022-06-24 06:42
@sayali-MSFT looks like we are not yet able to see the latest version yet for update inside our ms teams. Is this released worldwide?

**Comment by sayali-MSFT** [comment] 2022-06-24 06:58
@harkiratsaluja -Yes .last update date 21-06-2022.

**Comment by sayali-MSFT** [comment] 2022-06-27 13:51
@harkiratsaluja - Ok. We will check it and let you know.

**Comment by ramfattah** [comment] 2022-06-29 21:41
Ran into this issue while investigating https://github.com/microsoft/BotBuilder-Samples/issues/3778

The buttons seem to work, except for `Custom Form` & `YouTube` buttons where the HTML pages are not getting rendered.
Listed steps to repro here https://github.com/microsoft/BotBuilder-Samples/issues/3778#issuecomment-1163820067

Investigation so far has yet to yield the root cause of this issue.

**Comment by ChetanSharma-msft** [comment] 2022-06-30 03:31
@harkiratsaluja - Can you please check on the latest updates today and let us know whether you are still not able to see the latest version.

**Comment by ChetanSharma-msft** [comment] 2022-06-30 03:32
> Ran into this issue while investigating #3778
> 
> The buttons seem to work, except for [Custom Form](https://github.com/microsoft/BotBuilder-Samples/blob/df93f6fb5379215e53f74c113eb9a1b2196a5ba0/samples/javascript_nodejs/54.teams-task-module/bots/teamsTaskModuleBot.js#L48) & [YouTube](https://github.com/microsoft/BotBuilder-Samples/blob/df93f6fb5379215e53f74c113eb9a1b2196a5ba0/samples/javascript_nodejs/54.teams-task-module/bots/teamsTaskModuleBot.js#L44) buttons where the HTML pages are not getting rendered. Listed steps to repro here [#3778 (comment)](https://github.com/microsoft/BotBuilder-Samples/issues/3778#issuecomment-1163820067)
> 
> Investigation so far has yet to yield the root cause of this issue.

@ramfattah - Thanks for reporting this issue.
We will check it from our end and get back to you.

**Comment by sayali-MSFT** [comment] 2022-06-30 07:43
@ramfattah -We are unable to repro the scenario, It's working fine from our end.Could you please check it once with the updated version?
 Microsoft Teams Version 1.5.00.17705 (64-bit)-E
 Sample-https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/54.teams-task-module

https://user-images.githubusercontent.com/93527375/176621184-25443533-5951-4312-a09d-baab786ef7f2.mp4

**Comment by ramfattah** [comment] 2022-07-01 00:24
Thanks for the response @sayali-MSFT.
I've noticed sometimes the HTML pages works and sometimes it doesn't, the result seems to be inconsistent. 

Looks like Teams updated today to version 1.5.00.17867 (64-bit). It was last updated on 6/30/2022. 
I can give it another try and report back.

Thanks.

**Comment by ramfattah** [comment] 2022-07-06 21:45
Hi @sayali-MSFT @ChetanSharma-msft 

Looks like I'm not able to repro this issue anymore. 
Using Teams Version 1.5.00.17971 (64-bit), the [54.teams-task-module](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/54.teams-task-module) sample ran successfully without any issues. 

https://user-images.githubusercontent.com/38049078/177648822-03de3511-68cf-4122-bcd6-47b1e101b6e4.mp4



Thank you.

**Comment by sayali-MSFT** [comment] 2022-07-08 09:57
@harkiratsaluja - Could you please confirm if your issue has resolved or still looking for any help?

**Comment by ramfattah** [comment] 2022-08-05 23:37
Closing due to inactivity.

**Closed by ramfattah** 2022-08-05 23:37 UTC
Labels: bug, customer-reported, Bot Services, customer-replied-to, ExemptFromDailyDRIReport

**Comment by surya-rattle** [comment] 2023-03-15 04:50
@clearab We're facing this issue again, could you please re-open this issue? 

```
Details:
Desktop Teams Versioning: 1.6.00.1159 last updated on 2/10/23
Web Application: Both the desktop and web app freezes MS Teams on interacting the with Task module (buttons)
```
