### ISSUE TITLE
TypeError: Cannot set property closed of #<Readable> which has only a getter

### ISSUE THREAD

**Issue by denlai-mshk** [microsoft/BotBuilder-Samples#3890] opened 2023-06-14 22:24 UTC
## Sample information
1. Sample type: **samples**
2. Sample language: **nodejs**
3. Sample name: **45.state-management**

## Describe the bug
```

PS C:\CodeProject\BotBilder-Samples\botbuilder-samples\samples\javascript_nodejs\45.state-management> npm start

> state-management-bot@1.0.0 start
> node ./index.js

C:\CodeProject\BotBilder-Samples\botbuilder-samples\samples\javascript_nodejs\45.state-management\node_modules\restify\lib\request.js:848
    Request.prototype.closed = function closed() {
                             ^

**TypeError: Cannot set property closed of #<Readable> which has only a getter**
    at patch (C:\CodeProject\BotBilder-Samples\botbuilder-samples\samples\javascript_nodejs\45.state-management\node_modules\restify\lib\request.js:848:30)
    at Object.<anonymous> (C:\CodeProject\BotBilder-Samples\botbuilder-samples\samples\javascript_nodejs\45.state-management\node_modules\restify\lib\server.js:33:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\CodeProject\BotBilder-Samples\botbuilder-samples\samples\javascript_nodejs\45.state-management\node_modules\restify\lib\index.js:10:14)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)

Node.js v18.15.0
```
## To Reproduce
1. npm install
2. npm start

## Expected behavior
No error

**Comment by denlai-mshk** [comment] 2023-06-14 22:29
upgrade the Restify from package.json to
```
 "restify": "^11.1.0"
```
can fix this issue

**Comment by natrexjacobs** [comment] 2023-06-25 00:16
Can confirm updating `restify` will resolve the provided error - but I didn't get much further (looks like further API changes)

```
> tsc --build && node ./lib/index.js

node:assert:125
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Handler [handler-0 on POST /api/messages] is missing a third argument (the "next" callback) but is not an async function. Middleware handlers can be either async/await or callback-based.Callback-based (non-async) handlers should accept three arguments: (req, res, next). Async handler functions should accept maximum of 2 arguments: (req, res).
    at Chain.add (<path>\node_modules\restify\lib\chain.js:79:16)
    at forEach (<path>\node_modules\restify\lib\router.js:211:15)
    at Array.forEach (<anonymous>)
    at Router.mount (<path>\node_modules\restify\lib\router.js:203:14)
    at Server.serverMethod [as post] (<path>\node_modules\restify\lib\server.js:1750:33)
    at Object.<anonymous> (<path>\lib\index.js:59:8)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: 'Function',
  expected: 'AsyncFunction',
  operator: '=='
}

Node.js v18.16.1
```

tsc: 4.8.5
Windows / GitBash

**Comment by stevkan** [comment] 2023-07-05 23:28
Thank you for your patience.

In my own testing, I have found that the issue is originating in the creation of the Restify endpoints. They either need to be created with async/await or have the `next` callback assigned in the parameters (and called).

**async/await**
```js
server.post('/api/messages', async (req, res) => {
    // Route received a request to adapter for processing
    await adapter.process(req, res, async (turnContext) => {
        const { activity } = turnContext;
        this.activity = activity;

        console.log('ACTIVITY ', this.activity);

        await myBot.run(turnContext);
    });
});
```

**`next` callback** - calling `next()` may not be necessary as in my testing it worked with and without as long as it is assigned as a parameter.
```js
server.post('/api/messages', (req, res, next) => {
    // Route received a request to adapter for processing
    adapter.process(req, res, async (turnContext) => {
        const { activity } = turnContext;
        this.activity = activity;

        console.log('ACTIVITY ', this.activity);

        await myBot.run(turnContext);
    });
    next();
});
```

Please test if this solves the issue for you.

**Comment by stevkan** [comment] 2023-08-24 22:21
Closing as resolved.

**Closed by stevkan** 2023-08-24 22:21 UTC
Labels: bug, customer-reported, Bot Services, needs-triage

**Comment by liuclarahy** [comment] 2023-08-28 13:03
@stevkan Thanks for providing a fix. Where do I create the Restify endpoints with the async/await? Please kindly advise. thank you
