### ISSUE TITLE
Yeoman templates need to have their versions set in the package.json

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/BotBuilder-Samples#1395] opened 2019-04-10 18:00 UTC
The Samples build, which builds the Yeoman generators, needs to update the package.json files for the relevant yeoman templates. 

These should follow the standandard semver rules, and match the versions of the C# ones.

**Comment by BruceHaley** [comment] 2019-04-23 17:25
Need clarification: Is this a duplicate of issue #1394?

**Comment by BruceHaley** [comment] 2019-04-23 17:29
Relevant build: VSIX-From-botbuilder-samples-repo.

**Comment by BruceHaley** [comment] 2019-04-23 18:47
Version set. Example: 4.4.0-preview-142. (Target file for versioning was source.extension.vsixmanifest.)

**Closed by BruceHaley** 2019-04-23 18:47 UTC
Labels: 4.4, Approved, P1, Triaged
