### ISSUE TITLE
OnTeamsFileConsentAcceptAsync is not getting Fired

### ISSUE THREAD

**Issue by GaurangNaik** [microsoft/BotBuilder-Samples#3144] opened 2021-03-28 14:15 UTC
## Sample information
1. Sample type: [\samples\ or \solutions\]
2. Sample language: [dotnetcore]
3. Sample name: TeamsFileUpload

## Describe the bug
OnTeamsFileConsentAcceptAsync is not getting called however OnTeamsFileConsentDeclineAsync is getting fired correctly.

## To Reproduce
1. Hosted TeamsFileUpload sample on our Azure.
2. FileUpload needs permission to upload this file to your One Drive.
3. Clicked on 'Allow'
4. Nothing happens.

But when clicked on Declined it works as expected.

## Expected behavior
It should copy the file to One Drive and also should give prompt for downloading the file on local machine.

## Screenshots
None

## Additional context
This was working absolutely fine as I have created a separate bot and used Upload file and Download file functionality. It was working fine until last week but suddenly stopped downloading feature however uploading feature is working absolutely fine. Thus I tried to host the sample file just to check if I missed anything and check if File Upload is working fine or not but unfortunately this sample is also not working as it used to be.

Request you to please look into this.

Regards,
Gaurang Naik

**Comment by msomanathan** [comment] 2021-03-30 18:15
@GaurangNaik we are working on a major release, so apologies for the delay in getting to this issue. We will respond back with a resolution as soon as we can.

**Comment by peterinnesmsft** [comment] 2021-04-05 18:15
@jwiley84 can you provide an update on current status when you have a moment? Thank you!

**Comment by Zerryth** [comment] 2021-04-14 18:02
@GaurangNaik Wanted to let you know that I'm now looking into this ticket here.

Though trying to run sample [56.teams-file-upload](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/56.teams-file-upload) myself to try to repro your issue, but I'm having difficulty just getting the app/bot into Teams 😞 

<details>
    <summary> Upload Error Screen Shots</summary>
 
![image](https://user-images.githubusercontent.com/35248895/114757325-8f0d8e80-9d10-11eb-9127-c6ee4fa862c6.png)
![image](https://user-images.githubusercontent.com/35248895/114757401-aba9c680-9d10-11eb-81a2-ffb3a6230f68.png)

</details>

The error says "`App sideload for personal scope failed [Object object]`" 

*manifest.json*
```
      "scopes": [
        "personal"
      ],
```
___

Anyways, just wanted to update the thread that I'm looking into the issue. I'll report back once I have something more substantial to comment on

**Comment by Zerryth** [comment] 2021-04-14 20:35
Ok, so I managed to reproduce the bug, and it looks like this is an issue with Teams itself--more specifically the desktop client of Teams (as opposed to the web version).

___
### Repro
1. Use sample [56.teams-file-upload](https://github.com/Zerryth/investigations/blob/main/teams-file-upload/teamsFileUpload.gif?raw=true), setting up sideloading the bot to Teams
2. Try talking to the bot via desktop version of Teams
   * Nothing happens when either "Allow" or "Decline" are clicked  :confused:
3. Try talking to the bot via web version of Teams
   * Bot successfully responds

Took a screencap, below.
Left in black: Teams desktop
Right in light: Teams web app  
![Teams File Upload Bug](https://github.com/Zerryth/investigations/blob/main/teams-file-upload/teamsFileUpload.gif?raw=true)

___

@clearab how do we connect this to the right people on Teams? Or, if you have any other ideas on how to investigate ourselves, do share your wealth of Teams knowledge ☺️

**Comment by Zerryth** [comment] 2021-04-14 20:36
Also wanted to note that I just updated Teams desktop client to the latest, just in case. Still didn't get any response when clicking `Allow`/`Decline` for file upload

**Comment by Zerryth** [comment] 2021-04-22 17:12
@GaurangNaik I haven't been able to get an answer from people on the Teams team directly.

It seems like the best way to reach out to the Teams team is to file an issue--looks like one of their pipelines is via their desktop app

*bottom-left > Help > Report a problem*
![image](https://user-images.githubusercontent.com/35248895/115756630-1a130800-a353-11eb-8cbe-d51c88f26cfc.png)

*problem form*
![image](https://user-images.githubusercontent.com/35248895/115756407-0a93bf00-a353-11eb-90dd-66587dc21098.png)

Add details about how you encountered the issue--you could even include a link to the issue you filed here, if you want them to see my repro as well.
___

Closing the issue here, as the SDK team can only fix issues with the Bot Framework SDK itself and not the Teams client

**Comment by clearab** [comment] 2021-04-22 18:33
@Wajeed-msft Can you please take a look at this one? Let's see if we can do a bit of a warm hand-off to the Teams group.

**Comment by Wajeed-msft** [comment] 2021-04-27 15:49
@GaurangNaik - This is happening probably because supportsFiles is set to false for your Bot in Teams app manifest. 

![image](https://user-images.githubusercontent.com/31851992/116271398-92d3f300-a79d-11eb-8dcd-3b37032232af.png)

I have opened new issue on Teams side for tracking here: https://github.com/MicrosoftDocs/msteams-docs/issues/3185

**Closed by Wajeed-msft** 2021-04-27 15:49 UTC
Labels: Bot Services, bug, customer-replied-to, customer-reported, needs-triage
