### ISSUE TITLE
Resource temporarily unavailable error while starting the conversation

### ISSUE THREAD

**Issue by Vigneshramkumar** [microsoft/BotBuilder-Samples#3479] opened 2021-09-14 06:18 UTC
Hello All,

I am using Azure Bot service and Bot Framework V4(4.13.2) for my Chatbot and enabled MS Teams as a channel in Bot service. I am using Orchestrator as a dispatcher for finding the score to route the request to either LUIS or QnA Maker. It is working fine in emulator and I deployed it in Linux server.

While starting the conversation (by having a gap of 1 hour or so) I am getting below error in the bot framework. And when I ping again the Chatbot is working fine. I am not sure whether this is related to Orchestrator or LUIS/QnA Maker one. 
This error I am getting everytime I start the conversation (by having some time gap).

`fail: Microsoft.Bot.Builder.Integration.AspNet.Core.BotFrameworkHttpAdapter[0]
      Exception caught : Resource temporarily unavailable`

Kindly help me in solving the issue. I have other chatbots integrated with Teams and using QnA Maker via bot framework. I didn't get these kind of issues over there after deployment. Thanks in advance for your response.

In the Issues section I saw a similar issue [(Issue)](https://github.com/microsoft/BotBuilder-Samples/issues/2582) but not sure how it got solved, since the user didn't mention about the solution for the issue before closing the same.

**Comment by Vigneshramkumar** [comment] 2021-09-14 06:27
I am using both LUIS and QnA Maker. Also Orchestrator as a dispatcher tool. 
I am not getting the issue when I type a QnA Maker based query. It is working fine while starting a new conversation. I am only getting the error when I type any LUIS based query.
And if i retype the same query it works fine. There might be some timeout issue while calling the LUIS API. I am using Declarative adaptive dialog for bot framework dialogs.

**Comment by anusharr** [comment] 2021-09-14 16:57
Closing this issue as the issue is already opened in the [SDK repo](https://github.com/microsoft/botframework-sdk/issues/6380).

**Closed by anusharr** 2021-09-14 16:57 UTC
