### ISSUE TITLE
Teams asking user to enter 6 digit code?

### ISSUE THREAD

**Issue by catmanjan** [microsoft/BotBuilder-Samples#3779] opened 2022-06-20 03:03 UTC
## Sample information
[BotBuilder-Samples](https://github.com/microsoft/BotBuilder-Samples/tree/a66d06f7feff10168591cbac0181ae2ec09f29bd)/[samples](https://github.com/microsoft/BotBuilder-Samples/tree/a66d06f7feff10168591cbac0181ae2ec09f29bd/samples)/[csharp_dotnetcore](https://github.com/microsoft/BotBuilder-Samples/tree/a66d06f7feff10168591cbac0181ae2ec09f29bd/samples/csharp_dotnetcore)/[52.teams-messaging-extensions-search-auth-config](https://github.com/microsoft/BotBuilder-Samples/tree/a66d06f7feff10168591cbac0181ae2ec09f29bd/samples/csharp_dotnetcore/52.teams-messaging-extensions-search-auth-config)

## Describe the bug
When I deploy this sample the user is prompted to enter a 6 digit code to log in - however there is nowhere to enter it as they are accessing the bot as a compose message extension - I would expect either the user is not prompted and SSO happens, or they are asked to enter their credentials in the pop up that shows the 6 digit code

## To Reproduce
1. Deploy the sample in Azure
2. Try to use it

## Expected behavior
Users either don't get asked to log in, or they log in a normal username/password prompt rather than a 6 digit code

## Screenshots
![image](https://user-images.githubusercontent.com/137350/174517934-92346627-a8df-442c-9e63-8710acfbc212.png)

**Comment by ramfattah** [comment] 2022-06-20 17:09
Hello @catmanjan, I'm investigating this one.

**Comment by ramfattah** [comment] 2022-06-21 19:19
Hi @catmanjan 

Looks like I was not able to reproduce this issue.

Steps I took:
1) Clone sample[ 52.teams-messaging-extensions-search-auth-config](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/52.teams-messaging-extensions-search-auth-config) (main branch)
2) Added [authentication](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/add-authentication?tabs=dotnet%2Cdotnet-sample) to the Teams bot
3) Set up [ngrok](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/52.teams-messaging-extensions-search-auth-config#:~:text=Run%20ngrok%20%2D%20point%20to%20port%203978) tunneling solution
4) Updated [appsettings.json](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/52.teams-messaging-extensions-search-auth-config#:~:text=Update%20the%20appsettings,from%20starting%20ngrok) and [manifest.json](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/52.teams-messaging-extensions-search-auth-config#:~:text=This%20step%20is,a%20custom%20app%22)
5) Ran the bot and tested in teams


Attempted to login, It seems it did not ask for 6 digit secret. I logged in with email and password.
![image](https://user-images.githubusercontent.com/38049078/174879593-144bbc0a-13b9-4071-8697-8ad793f1a3e3.png)


After login
<img src="https://user-images.githubusercontent.com/38049078/174879264-98a43055-6ac8-4da5-9f35-6ca4d630c5bd.png" width="500"/>

#

I noticed in your attached link
> [BotBuilder-Samples](https://github.com/microsoft/BotBuilder-Samples/tree/a66d06f7feff10168591cbac0181ae2ec09f29bd)/[samples](https://github.com/microsoft/BotBuilder-Samples/tree/a66d06f7feff10168591cbac0181ae2ec09f29bd/samples)/[csharp_dotnetcore](https://github.com/microsoft/BotBuilder-Samples/tree/a66d06f7feff10168591cbac0181ae2ec09f29bd/samples/csharp_dotnetcore)/[52.teams-messaging-extensions-search-auth-config](https://github.com/microsoft/BotBuilder-Samples/tree/a66d06f7feff10168591cbac0181ae2ec09f29bd/samples/csharp_dotnetcore/52.teams-messaging-extensions-search-auth-config)

The sample is not on main branch and its TargetFramework is .netcore 2.1 with outdated packages.
https://github.com/microsoft/BotBuilder-Samples/blob/a66d06f7feff10168591cbac0181ae2ec09f29bd/samples/csharp_dotnetcore/52.teams-messaging-extensions-search-auth-config/TeamsMessagingExtensionsSearchAuthConfig.csproj#L4

#

Have you tried running the sample from the main branch?
https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/52.teams-messaging-extensions-search-auth-config

**Comment by catmanjan** [comment] 2022-06-24 02:15
Yes I've tried that, note that I am deploying the app to my organisation through Teams administration rather than through "Upload an app" in the teams client

**Comment by catmanjan** [comment] 2022-06-24 02:29
Also I am not using ngrok because the app was deployed to Azure as it would be in a real scenario

**Comment by catmanjan** [comment] 2022-06-24 02:30
Here's a Fiddler trace of the requests that happen between me clicking "Sign in" and the 6 digit code appearing

![image](https://user-images.githubusercontent.com/137350/175450337-94d68718-adb5-47bc-805d-715aa85a57fa.png)

**Comment by catmanjan** [comment] 2022-06-24 02:34
Also, one last thing, I noticed that I don't get prompted to provide a 6 digit code when using the web version of Teams, it only happens in the desktop version

In fact on the web I don't even get asked to pick an account, I just click sign in, a pop up briefly appears and then I get search results

ALSO further to this - after clicking sign in from the web version of Teams, the desktop version is no longer showing the 6 digit code - so I think there is some bigger issue at play here with the desktop version of Teams

**Comment by ramfattah** [comment] 2022-06-27 16:07
Thank you for the update @catmanjan, we are investigating further.

**Comment by ramfattah** [comment] 2022-07-08 06:26
Hi @catmanjan 

After [publishing the bot to azure](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=multitenant%2Cnewgroup%2Ccsharp), it seems I'm not able to reproduce this issue. 

It gives the option to log in with a username and password and not 6 digit code. 
Note, I uploaded the manifest.zip to Teams (in the Apps view click "Upload a custom app")

Using Teams Version 1.5.00.17971 (64-bit).

#

> note that I am deploying the app to my organisation through Teams administration rather than through "Upload an app" in the teams client

Perhaps this might be the cause of this issue?

**Comment by axelsrz** [comment] 2022-07-19 17:27
Hello @catmanjan in order to proceed with the ticket, could you please provide an update regarding this message? 

> Hi @catmanjan
> 
> After [publishing the bot to azure](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=multitenant%2Cnewgroup%2Ccsharp), it seems I'm not able to reproduce this issue.
> 
> It gives the option to log in with a username and password and not 6 digit code. Note, I uploaded the manifest.zip to Teams (in the Apps view click "Upload a custom app")
> 
> Using Teams Version 1.5.00.17971 (64-bit).
> 
> > note that I am deploying the app to my organisation through Teams administration rather than through "Upload an app" in the teams client
> 
> Perhaps this might be the cause of this issue?

**Comment by catmanjan** [comment] 2022-07-19 23:17
@axelsrz sure, what update do you need? I explained my reproduction steps in detail above

**Comment by munozemilio** [comment] 2022-08-10 21:31
@catmanjan are you getting the same issue if you upload the manifest.zip to Teams (in the Apps view click "Upload a custom app")

**Comment by catmanjan** [comment] 2022-08-10 22:34
No I only saw the issue when deploying the app to the organisation

**Comment by ramfattah** [comment] 2022-08-23 22:49
Hi @catmanjan,

Looks like uploading the bot to Teams using Microsoft Teams admin center (https://admin.microsoft.com/) is the root cause of this issue.

I'm Investigating further for the next steps.

**Comment by catmanjan** [comment] 2022-08-24 01:00
Thanks we're still invested in getting this fixed

**Comment by ramfattah** [comment] 2022-09-06 02:46
Hi @catmanjan, 

The "Microsoft Teams" team was also not able to reproduce this issue using Teams admin center. 

From Teams:
> It did not ask for 6 digit secret. It logged in with mail Id and password.
>
> Attaching screenshot for reference:
> ![MicrosoftTeams-image](https://user-images.githubusercontent.com/38049078/188536243-2129ae62-eb46-4040-b05e-76f1b21b03ba.png)


 
> ![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/38049078/188536253-7fdf8e66-df87-4917-b6a6-c730099a48b7.png)

**Comment by ramfattah** [comment] 2022-09-06 02:48
Closing this issue as we are not able to repro.

**Closed by ramfattah** 2022-09-06 02:48 UTC
Labels: customer-reported, Bot Services, customer-replied-to
