### ISSUE TITLE
18.bot authentication, Does not allows to enter the credentials in oauth prompt 

### ISSUE THREAD

**Issue by prakash9707** [microsoft/BotBuilder-Samples#1595] opened 2019-06-25 10:09 UTC
I used azure active directory v2 connection and I created a azure application with allows users to login with multiple organization. After this when I runs this code it displays a empty window and takes the account which is previously logged in.

For the first time it allows me to enter the microsoft email and password. After when I type "logout" then I does not allow me to enter the username and password.

I think it does not logout the user properly. My azure application redirect url or reply url is "https://token.botframework.com/.auth/web/redirect" and logout url is empty.

In the azure active directory v2, I had given my tenant id as "common". I think the problem is with the azure connections. 

when I press login in oauth card, I got the below response and after a couple of seconds it will disappear automatically. What may be the issue?

![bug](https://user-images.githubusercontent.com/41231971/60089853-fbe01f00-975e-11e9-9b59-7b5b5f0a3a27.png)

[bug]

**Comment by CoHealer** [comment] 2019-07-01 19:56
@jwiley84, please investigate

**Comment by jwiley84** [comment] 2019-07-01 21:57
This seems to be a behaviour limited to the emulator, as that is the only channel I can reproduce it in. Let me reach out to a member of their team. The standard webchat (not the Azure's 'Test in WebChat') allows for 're-logging', if you will.

**Comment by jwiley84** [comment] 2019-07-03 16:23
Hi @prakash9707! I got a response from the emulator team. They've recently implemented some changes in how ngrok is being used with OAuth prompts. The details are [here](https://github.com/microsoft/BotFramework-Emulator/pull/1660). Try to update your emulator and give it another shot.

**Comment by CoHealer** [comment] 2019-07-11 21:13
@prakash9707 , did this resolve your issue?

**Comment by jwiley84** [comment] 2019-07-17 16:14
Closing issue.

**Closed by jwiley84** 2019-07-17 16:14 UTC
Labels: Support
