### ISSUE TITLE
Fix typo in JS Yeoman generator

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/BotBuilder-Samples#935] opened 2018-10-30 17:20 UTC
## Issue
There's a typo in the default description in the generator (generator-botbuilder).

> Logging the issue here, since it's the one the [npm package](https://www.npmjs.com/package/generator-botbuilder) points to.

## Repo steps

1. Start the generator and look at the default text for the description.
1. Error: there's a missing **i** in the word **capabilities** in the description.
   ```text
   ? What will your bot do? Demonstrate the core capabilties of the Microsoft Bot Framework
   ```

**Comment by sgellock** [comment] 2018-11-17 00:01
The repo that @nyxsys references above is not the currently supported repo that has the botbuilder yeoman generator.  The officially supported repo for the yeoman generator is located at:  
https://github.com/Microsoft/BotBuilder-Samples/tree/master/generators/generator-botbuilder

The issue is fixed in 4.0.13 or higher

**Closed by sgellock** 2018-11-17 00:01 UTC
Labels: 4.2, Approved, P1

**Comment by JonathanFingold** [comment] 2018-11-17 00:11
@sgellock For the the **homepage** and **repository** links on the [npm page](https://www.npmjs.com/package/generator-botbuilder), can you update them to point to the new repo/location?

**Comment by JonathanFingold** [comment] 2018-11-19 17:30
@sgellock Can we add a section/link in the README to the correct issues page for this project, to reduce this sort of confusion in the future?
